### ISSUE TITLE
User Story: Pilot department needs help setting milestones for transitions to ensure they continue transitioning content using service-oriented language.

### ISSUE THREAD

**Issue by LCTrujillo** [cityofaustin/techstack#1]
Complete Funshop Session III

- [x] Create homework assignment

- [x] Send homework assignment to participants

- [x] Draft slides for creating meta data

- [x] Refine deck

- [x] Run-through Funshop III
