### ISSUE TITLE
Police Oversight form: OPO-only "microsite" on Alpha.austin.gov

### ISSUE THREAD

**Issue by easherma** [cityofaustin/techstack#1236]
Just going more or less top to bottom and charting out the differences between v1, the microsite, and v2 of janis.

Easy + Global:

- [x] Colors

- [x] Fonts

- [x] Language picker can remain it's own menu and stack (mocks have it inline with the page header/nav)

Micro-site Specific Stuff:
- [ ] OPO Department page breadcrumb

- [ ] WIP footer can get added to all of alpha, we'll think about how that works or dosen't with the current component structure

- [ ] Menu/Nav is pretty different, but could be written to eventually incorporate into janis v2

Conflicts:

- [ ] At first glance, overall layout is pretty different

- [ ] Page Section header (aka nav bar) is very different, do we hide it, refactor it, write a new one, or limit the page sections to valid links?

![Space Jam](https://media.giphy.com/media/8CSflsMG1IFos/giphy.gif)

**Comment by amenity** [comment]
Thanks, @easherma! 
Re: layout - note that the microsite only includes information pages and a department page, and those templates are not in use on the rest of the site at the moment.

**Comment by easherma** [comment]
@amenity true, my concern re: 'conflicts' is more the other way around: where these templates use components that are also used by other parts of the site, where the line is between modifying them vs rolling new ones :-D

**Comment by amenity** [comment]
Now a duplicate of #1271
