### ISSUE TITLE
Decide what to do with homelessness assistance content

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1420]
Draft: https://docs.google.com/document/d/1ffA7cWBJNM_nSix3RTju6cLWuFZ4l61NTtak8VoM4aY/edit?usp=sharing

Revisit with the help of Taylor and Sarah Rodriguez.

Link to non-transitioning austintexas.gov pages, such as:
- [ ] http://www.austintexas.gov/department/special-projects-and-community-programs
- [ ] http://www.austintexas.gov/department/permanent-supportive-housing-initiative
- [ ] http://www.austintexas.gov/page/tenant-relocation-assistance-policy-development

**Comment by desigonz** [comment]
Meet with Taylor and Sarah Rodriguez on 4/4. Notes from meeting in the doc: https://docs.google.com/document/d/1ffA7cWBJNM_nSix3RTju6cLWuFZ4l61NTtak8VoM4aY/edit?usp=sharing

Next step is to draft as a process page.

**Comment by desigonz** [comment]
Draft info page that:
- Gives a brief snapshot of the issue
- Lists all of APH’s partners/contracts that it funds
- Lists outcomes of these programs
- Links to Auditor’s Office reports on homelessness

User: Journalists, council members, and other stakeholders who want to know how the City is addressing homelessness

from: https://docs.google.com/document/d/1SaAfqOz2VUycMEXqXje5sVTMaAapyB1HXUHnWWzjabY/edit?usp=sharing
