### ISSUE TITLE
OPO media push: Thank you form landing page

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1431]
### English
_https://forms.austintexas.io/police-thank/introduction_
- [x] `<title>` should be "Thank an Austin police officer"
- [x] Change "Time" "Date and time" and move to  _Optional Information_
- [x] Under _In person_, remove " You will need to check in with building security at the front desk."
- [x] Under _In person_, remove extra period #1350  

### Spanish
_https://forms.austintexas.io/policia-agradezca/introduccion_ 
- [ ] `<title>` should be "Agradezca a un oficial de policía de Austin"  - #1504 
- [x] Change "Hora" to "Fecha y hora" and move to "Información opcional"
- [x] Under _En persona_, remove "Deberá presentarse con el personal de seguridad en la entrada."
- [x] Under _En persona_, remove extra period #1350

**Comment by desigonz** [comment]
@easherma See the `<title>` checkboxes above—I believe those have been taken care of by [#1383](https://app.zenhub.com/workspaces/office-of-design-and-delivery-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/1383), correct?

**Comment by desigonz** [comment]
@easherma Oh and I'm noticing that the right titles are pulling in for English but not for Spanish on both the thank you and complaint forms. If I add that to translations.json, will it work?

**Comment by easherma** [comment]
@desigonz yes you should be able to add to translations.json

**Comment by desigonz** [comment]
- [ ] Add `<title>` translation to thank you form json 
- [ ] Add `<title>` translation to complaint form json

**Comment by desigonz** [comment]
@amenity Moving to QA. I wasn't able to translate `<title>` via translations.json, should that be a new issue for devs?

**Comment by amenity** [comment]
@easherma can we just update the title here? 
https://github.com/cityofaustin/officer-thank-form/blob/946aafa0adcb1ffa16e51537c8bcc78c77908671/package.json

**Comment by amenity** [comment]
Title issue here: https://github.com/cityofaustin/techstack/issues/1504
