### ISSUE TITLE
Moving from Microsite to Full site

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#1528]
**What we need to do to get the microsite to where we want it to be:**
- [x] Fix social media urls https://github.com/cityofaustin/techstack/issues/1530 (or ideally https://github.com/cityofaustin/techstack/issues/1403)
- [x] Fix whatever is causing department page to not be bigger than full width on mobile https://github.com/cityofaustin/techstack/issues/1531
- [x] Make hours on contact information look better https://github.com/cityofaustin/techstack/issues/1532
- [x] Fix overlapping heading text on department page in Spanish on mobile https://github.com/cityofaustin/techstack/issues/1533
- [x] Ensure proper OPO menu behavior on mobile https://github.com/cityofaustin/techstack/issues/1534
- [x] Make mobile footer look better https://github.com/cityofaustin/techstack/issues/1535
- [x] Make mobile heading padding match designs https://github.com/cityofaustin/techstack/issues/1536
- [x] Fix OPO breadcrumb in Spanish, it's giant on mobile https://github.com/cityofaustin/techstack/issues/1537 
- [x] Verify all OPO pages with design/content to make sure we aren't missing anything

**What we need to do to move from the microsite to the full site:**
- [x] Move back to the old nav menu https://github.com/cityofaustin/techstack/issues/1529
- [x] Switch away from using hardcoded social media https://github.com/cityofaustin/techstack/issues/1403
- [ ] Make janis prod not a manual deployment (look for issue)
- [ ] Verify ***ALL*** pages with design/content to make sure we have them implemented correctly.

**Current state of things in Janis staging - building from Joplin prod:**

Janis links for all pages in Joplin prod (as of 11:30PM on 2019/03/19):
* Complaint investigation process (information page)
  * https://janis-staging.herokuapp.com/police-oversight/complaint-investigation-process
* How we store and use your data (information page)
  * https://janis-staging.herokuapp.com/police-oversight/how-we-store-and-use-your-data
* Office of Police Oversight (department page)
  * https://janis-staging.herokuapp.com/police-oversight
* Learn how to prevent the flu (information page)
  * https://janis-staging.herokuapp.com/health-safety/healthcare-prevention/learn-how-to-prevent-the-flu
* Prevent measles in Austin (information page)
  * https://janis-staging.herokuapp.com/health-safety/healthcare-prevention/learn-about-measles-in-austin
* Privacy policy for Alpha.Austin.gov (information page)
  * https://janis-staging.herokuapp.com/government-business/city-code/privacy-policy-for-alphaaustingov
* Get a birth or death certificate (service page)
  * https://janis-staging.herokuapp.com/health-safety/records-and-certificates/birth-and-death-certificates
* Interior Remodel (process page)
  * https://janis-staging.herokuapp.com/permits-tickets/building-permits/interior-remodel
* Learn more about Austin Resource Recovery (department page)
  * https://janis-staging.herokuapp.com/learn-more-about-austin-resource-recovery
* File a complaint against an Austin Police Officer (information page)
  * https://janis-staging.herokuapp.com/health-safety/police-reports-records/file-a-complaint
* Learn how to prevent crypto and other waterborne diseases (information page)
  * https://janis-staging.herokuapp.com/health-safety/healthcare-prevention/learn-how-to-prevent-crypto-and-other-waterborne-diseases
* Get ready for curbside compost pickup (service page)
  * https://janis-staging.herokuapp.com/housing-utilities/recycling-trash-compost/compost-pickup
* Get ready for curbside bulk item pickup (service page)
  * https://janis-staging.herokuapp.com/housing-utilities/recycling-trash-compost/bulk-item-pickup
* Set out your leaves, grass, and branches for pickup (service page)
  * https://janis-staging.herokuapp.com/housing-utilities/recycling-trash-compost/set-out-your-leaves-grass-and-branches-for-pickup
* Look up your trash, recycling, and compost pickup days (service page)
  * https://janis-staging.herokuapp.com/housing-utilities/recycling-trash-compost/trash-recycling-pickup
* Pick up free paint and other household items (service page)
  * https://janis-staging.herokuapp.com/housing-utilities/recycling-trash-compost/pickup-free-paint
* Prepare for public health emergencies (service page)
  * https://janis-staging.herokuapp.com/health-safety/healthcare-prevention/public-health-emergency-prep
* Drop off household hazardous waste and other recyclables (service page)
  * https://janis-staging.herokuapp.com/housing-utilities/recycling-trash-compost/hazardous-waste-dropoff
* Get immunizations for you and your family (service page)
  * https://janis-staging.herokuapp.com/health-safety/healthcare-prevention/get-immunized
* Find free condoms and learn other ways to prevent HIV (service page)
  * https://janis-staging.herokuapp.com/health-safety/healthcare-prevention/find-free-condoms

**Comment by pibemillo** [comment]
https://github.com/cityofaustin/janis/pull/343 for https://github.com/cityofaustin/techstack/issues/1537
