### ISSUE TITLE
Draft immunizations content

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#1614]
http://www.austintexas.gov/immunizations

how does this work with other vaccine info?

**Comment by desigonz** [comment]
We've ended up splitting up immunization in a number of service pages. 
- [ ] [Get immunizations for you and your family](https://joplin.herokuapp.com/admin/pages/9/edit/)
- [ ] [Get a flu shot](https://docs.google.com/document/d/11wKjhYakpjhIFqz67G7m2IqyQ5EB6C8Or90zYvdvsUQ/edit?usp=sharing) (note: I've taken out information about preventing the flu since that live in the [flu prevention](https://joplin.herokuapp.com/admin/pages/32/edit/) info page)
- [ ] [Get a copy of your immunization record](https://docs.google.com/document/d/1gC5eOWnzxeL_Kwi7FGFFoiQGBE2myShO1QbKam-NPk8/edit?usp=sharing) 

A few outstanding questions:
- [ ] Vaccines for Children program on the immunizations page is super vague; difficult to know if/how residents can access it. I'm asking Sarah Rodriguez to clarify.
- [ ] On the [Get immunizations for you and your family](https://joplin.herokuapp.com/admin/pages/9/edit/) service page, we have some content that is redundant of the [Get a copy of your immunization record](https://docs.google.com/document/d/1gC5eOWnzxeL_Kwi7FGFFoiQGBE2myShO1QbKam-NPk8/edit?usp=sharing) service page. My recommendation is to the content shorten it on the former and link out to the source of truth on the latter (for example, don't mention ImmTrac, so we don't have to update in two places). ALTERNATIVELY, I know someday we'll have "related services" appearing on a page—would be great to connect that way.

**Comment by desigonz** [comment]
@LauraTrujillo, assigning you to review these, and please check out my note above about redundancy! I took a holistic look at the existing immunizations content and have one big question still. (Also, since I updated existing/previously revised drafts, I don't think we need to do two rounds of review.)

**Comment by LauraTrujillo** [comment]
@desigonz Reviewed with some comments. I agree with your recommendation in an earlier comment. Let's shorten the service page (Get immunizations) and remove mention of ImmTrac. Let me know if you have the bandwidth to make the changes, or if you want me to do.

**Comment by desigonz** [comment]
@LauraTrujillo Just did it—thank you!
