### ISSUE TITLE
Draft injury prevention content

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#1615]
http://www.austintexas.gov/department/injury-prevention

**Comment by desigonz** [comment]
@LauraTrujillo Would love to get your thoughts on the injury prevent page. It's a BIG catch-all culprit. 

Here's my summary of what's happening on the page and possible directions for the content:

- [ ] **Safe sleep for infants** "Contact Denise Geleitsmann for a presentation on best practices in safe sleep for infants or to learn more about the Safe Sleep Coalition" is the closest thing to a service here—but really there's no more information. Could be a service page, but we might have to do some more digging.
- [ ] **Child passenger safety** I revised the existing [Get a free child car seat check](https://docs.google.com/document/d/1Vx7w4fGwk3ZAO7BQnuZgCcl-HJtfUw8Y1xa6GZn4IpM/edit?usp=sharing) service page (it needs to go through the approval process; will do so when we figure out what to do with everything here)
- [ ] **Vision zero** this project is run by Transportation. I say we don't transition it (but could maybe link to it below; see "Overall")
- [ ] **Bike safety** it just links to other org's resources
- [ ] **Distracted driving** links to the hands-free ordinance page (which is APD, so let's wait to transition). Otherwise links to another org's resource
- [ ] **Falls preventions** the Stepping On program is mentioned, but there's even more info about it on [Healthy Places Healthy People](https://www.healthyplaceshealthypeople.org/mycommunity/). I say we make a service page
- [ ] **Drowning prevention** it just links to other org's resources and a community partner. Not sure if that's an official APH partner (like—do they underwrite the program?)
- [ ] **Suicide prevention** links to another org's resource

**Overall**
We COULD make an Injury Prevention Program info page that has bullet points of what the program covers, and MAYBE include a few learn more links. Is that getting into dangerous catch-all territory? Or could this be a good solution to make the people who runs this office feel represented?
I wonder if grouping some of these in a topic page would also make them feel represented. It wouldn't necessarily cover the areas that CoA doesn't provide a concrete service for, though.

**Comment by JeffCopy** [comment]
Cool, i will get my head around it and weigh in.

**Comment by desigonz** [comment]
Okay thanks for those recs @LauraTrujillo! Here's a summary of what I'm thinking for each. If it's medium/long backlog, then we won't work on it for the big APH push but do it after; the thinking is that it's brand new content that will require research/working closely with subject matter experts, so no longer a simple transition. I'll create the issues tonight.

- [ ] **Safe sleep for infants** *Create new issue and add to medium/long backlog: Safe sleep for infants info page; work with Denise Geleitsmann to share best practices and share contact information to learn more*
- [ ] **Child passenger safety** *Ready for approval: [Get a free child car seat check](https://docs.google.com/document/d/1Vx7w4fGwk3ZAO7BQnuZgCcl-HJtfUw8Y1xa6GZn4IpM/edit?usp=sharing) service page*
- [x] **Vision zero** *don't transition*
- [x] **Bike safety** *don't transition*
- [x] **Distracted driving** *don't transition*
- [ ] **Falls preventions** *Draft Stepping on service page*
- [ ] **Drowning prevention** *Create new issue and add to medium/long term backlog: Drowning prevention info page*
- [ ] **Suicide prevention** *Create new issue and add to medium/long-term backlog: suicide prevention info page*
- [ ] **Injury prevention topic page** *Need to draft*

**Comment by desigonz** [comment]
@JeffCopy, since you're reviewing #2295, do you mind also reviewing the [Get a free child car seat check](https://docs.google.com/document/d/1Vx7w4fGwk3ZAO7BQnuZgCcl-HJtfUw8Y1xa6GZn4IpM/edit?usp=sharing) service page draft? (Everything else on the list above should be taken care of in other issues.)

**Comment by JeffCopy** [comment]
Both 2295 and Get a free child car seat both now have my (minor) suggested revisions. Onward!

**Comment by desigonz** [comment]
Laura, sending you the [Get a free child car seat check](https://docs.google.com/document/d/1Vx7w4fGwk3ZAO7BQnuZgCcl-HJtfUw8Y1xa6GZn4IpM/edit?usp=sharing) service page for second review.

**Comment by LauraTrujillo** [comment]
@desigonz reviewed the car seat check- good to go there!
