### ISSUE TITLE
Draft Austin Energy Final Report

### ISSUE THREAD

**Issue by LauraTrujillo** [cityofaustin/techstack#1666]
Draft: https://docs.google.com/document/d/1kix-aX0I9fqM_f05-X3Wk1SREq1lFYzbERB3cTmQFc0/edit#heading=h.6lcq7jko6fwt

- [x] Executive summary (Taylor)
- [ ] Introduction
- [x] Background (project charter, the project came out of white paper, etc...)
- [x] Methodology
-- Governance and tech (internal stakeholders) Andrew and Michael
-- Content strategy (Laura and Andrew)
- [x] Rationale (Laura and Michael)
- [ ] Insights (Manlin) 
-- Customer insights (Laura and Andrew)
- [x] Recommendations- connect insights to recommendations and give a rationale (Laura, Andrew, and Manlin)
- [x] Conclusions (Taylor)
- [ ] Jeff reviews for unified voice and tone

**Comment by LauraTrujillo** [comment]
@stephaniegates tagging you in this issue just so you know what's going on
