### ISSUE TITLE
Guide content type visual design exploration

### ISSUE THREAD

**Issue by chasechenevert** [cityofaustin/techstack#1706]
Building on Tori's mockups, how will this fit into Alpha

### Related issues
- #1717 How do users know a page on Alpha is part of a guide, if they arrive there not via the guide?
- #1718 How are guides represented on topic pages?

### Questions for consideration that might be further down the road
- [x] How might we display downloads
- [ ] How might we display Guide links on other page types throughout Alpha? Which page types, and where?

### Elements needed
- [x] Contacts and resources, and view this page on alpha
- [x] Page header
- [x] Section header
- [x] Table of contents (especially for mobile)
- [x] CSS checkbox for steps
- [ ] Cost tables?

**Comment by chasechenevert** [comment]
Here are the [very early rough drafts](https://drive.google.com/drive/u/0/folders/1iMMTbiKelMljuiT8NcQmnuTxp7rHA1Ff) that lead up to the MVP we're working through now
