### ISSUE TITLE
Janis 2 scrubbing and polish

### ISSUE THREAD

**Issue by chasechenevert** [cityofaustin/techstack#1712]
All the small little issues and tweaks needed for this early MVP of Janis 2. I'll break this issue into smaller issues later.

**General** 
- [x] Increase spacing between footer and page body content. Change to 80px (token=10)
- [x] Remove rule line between headings and body copy

**Navigation**

- [x] link-out icon: should be changed to material design's icon
- [x] AIRPORT: change to sentence case "Airport"
- [x] Languages: the selected language should be set in medium weight
- [x] Official site banner: currently only the plus/minus icons open and close the accordion. Let's make the entire label area be clickable
- [x] Click-off: on desktop a user should be able to click away from from the navigation to close the menu

Global navigation link styling: when set against blue background
- [x] default text-color should be #FFFFFF at 75% opacity
- [x] hover: opacity 100%
- [x] Megamenu (temporary one that we have now) sometimes appears _under_ "related services" block. [add in specific pages]

**Service page**
- [x] Banner height should be 380px min (excluding ContextualNav)
- [x] Padding on the bottom of the banner should be 80px high 
- [x] Rule color between ContextualNav and page header to #D9E8F6

**Forms**
- [x] Accordions: change to Material icons for plus and minus instead of USDS defaults

**Comment by easherma** [comment]
@chasechenevert are these changes you're expecting dev to work on at this time or are splitting them up for later? In which case they might be better for a Janis 2.1 than 2.0?

**Comment by oliver2g** [comment]
@chasechenevert will it be possible to make an epic and break this issue up into smaller chunks? For sprint/release planning purposes, we want to know what is MVP and what can go into later releases. Let me know if you need any help with this.

**Comment by chasechenevert** [comment]
I can turn this into an epic. 

The below issues (from the full list) I consider high priority because they deal with important interactions relating to primary nav: 
- [ ] Official site banner: currently only the plus/minus icons open and close the accordion. Let's make the entire label area be clickable
- [ ]  Click-off: on desktop a user should be able to click away from from the navigation to close the menu

**Comment by oliver2g** [comment]
Great, thanks @chasechenevert . When you break the above issues out, please add them to the "Janis 2.0 MVP" release. We'll also see where they fit in during Sprint planning. Thanks!

**Comment by sergiogcx** [comment]
A good chunk of these have been completed, the majority are shown within a single branch:

https://janis-pr.austintexas.io/422/



Issues fixed by this branch:

https://app.zenhub.com/workspaces/office-of-design-and-delivery-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/2097
https://app.zenhub.com/workspaces/office-of-design-and-delivery-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/2088
https://app.zenhub.com/workspaces/office-of-design-and-delivery-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/2011
https://app.zenhub.com/workspaces/office-of-design-and-delivery-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/2084
https://app.zenhub.com/workspaces/office-of-design-and-delivery-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/2009
