### ISSUE TITLE
Clean up coa-forms

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#1738]
The consolidated repo works, but it needs a little bit more work still.
- [x] #1743 Pass env variables to FileUploadWidget
- [x] #1739 Set up nginx for dev branch routing
- [x] https://github.com/cityofaustin/coa-forms/pull/10 Make Documentation more thorough about interconnected parts.
- [x] https://github.com/cityofaustin/coa-forms/pull/10 Make a couple more development helper scripts (install all dependencies)
- [x] Make Spanish Translation work locally with a yarn script
- [x] Make env variable for links back to Janis
- [ ] parallelize webpack builds
- [x] #1737 nest dev branch deployment buckets better. Try /form/branch/ rather than all /from-branch/ being on the same top level
- [ ] Improve logging during build process
- [ ] Finish formBuilder cli
- [ ] Separate out steps in circleci
- [ ] Run all test scripts for forms in circleci
- [ ] Add a git warning on push about the forms that will be deployed
- [ ] Make script to delete folders in S3 bucket if the branch is deleted in github
- [ ] Apply Janis-style versioning for Production Forms

**Comment by easherma** [comment]
@Niicck any of those above unchecked things that we should address and/or split into separate issues to note in the backlog?
