### ISSUE TITLE
Regression Testing: The Epic

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#1750]
**What** is regression testing? "This is where we test the app overall to make sure merging all these changes didn’t introduce new problems or resurface old bugs" -Sherman.

**Why** is this a good time to do regression testing?

SURPRISE! Under the cover of darkness, Sergio masterfully transferred our OPO staging environment from the old forms repo to the new one.

Its the same link: https://forms.austintexas.io/police-complain/introduction
but now it's using the code from our fabulous new consolidated https://github.com/cityofaustin/coa-forms architecture.

And it's basically the same! It's probably the same. It's hopefully the same. But we're going to test to make sure. That's what we will do today. Today, Wednesday, April 23rd. This is the test plan that we will execute. And then if it all looks super good, at the stroke of *midnight* Sergio and I will switch production over to our new forms repo. And the transformation will be complete.

Since this is a big change, it is *incumbent* on us to test it out thoroughly. We want to catch the bugs. We don't want users to catch the bugs. Because they don't have any way to report- ANYWAYS I'm going to propose a ludicrously thorough and comprehensive test plan. Feel free to push back/add to it as desired. But you know what. If nothing else, this can serve as a future template for the automated testing our future QA person is going to do with Selenium. So maybe not wasted effort. Maybe.

The plan in a nutshell. We need to test:
- all supported/important devices+browsers
- all 4 forms (complaint, thanks, queja, agradezca)
- all features in each form

Everyone gets assigned a browser/device. They go through all 4 forms for that device. If there are struggles, make issues with a "Bug" label and priority. P1 is highest, P5 is lowest. P3 and above are showstoppers and should be fixed before a switch to production- but only if they're unique to this new codebase (i.e. not something that was a problem with the old form also). Also, everything is negotiable.

Couple suggestions:
- There's a lot of checkboxes. They're annoying to click in github. Only check them if there was an issue, other leave them be.
- On the "received ticket" part of /what-happened, enter the name of your device+Browser as the name of ticket. That way we can trace the email response back to you if there was a problem.

Here are the devices to test:

Mobile:
- [ ] iPhone 6: Safari 11
  - Previously, this was Safari 12. But Annie and I thought that didn't make sense. If anyone wants to fight me on this, I'm open to hearing why I'm wrong.
- [ ] Android: Chrome 71.0

Desktop:
- [ ] Windows 10: Chrome 71.0
- [ ] Windows 7: Chrome 71.0;
- [ ] Windows 7: Internet Explorer 11
- [ ] MacOS 10.14: Chrome 71.0
- [ ] MacOS 10.14: Safari
  - Not on the old list, but it makes sense right?
- [ ] Windows 10: Edge 17.17;
- [ ] Windows 10: Internet Explorer 11
- A thought: Should we test Firefox? Only nerds use Firefox. And in my experience, lots of UI bugs in Firefox are fixed by fixing similar bugs in Safari and IE.

Here are them features to test:
- [ ] /introduction
  - [ ] Do the accordion buttons work?
- [ ] /what-happened
  - [ ] Are "Required" fields required? (Can you not proceed until you've filled out an answer?)
  - [ ] DatePicker
    - [ ] Can you enter a date?
    - [ ] Does it autocorrect if you try to enter a future date?
    - [ ] Does it autocorrect if you try to enter a date that doesn't exist (like February 31st)?
    - [ ] Is the date entered reflected in the calendar?
    - [ ] Is the date selected in the calendar reflected in the input boxes?
  - [ ] TimePicker
    - [ ] Can you enter a time?
    - [ ] Are you prevented from entering a fake time?
  - [ ] Received a Ticket
    - [ ] Enter the name of your device+Browser as the name of ticket. That way we can trace the email response back to you if there was a problem.
- [ ] /where-happened
  - [ ] Are "Required" fields required? (Can you not proceed until you've filled out an answer?)
  - [ ] LocationPicker
    - [ ] Can you set a location by entering the "Four Seasons"?
    - [ ] Can you set a location by entering "800 Guadalupe"?
    - [ ] Can you set a location by dragging the icon somewhere?
    - [ ] If you clear/x out the location, does the page prevent you from going forward?
- [ ] /share-evidence
  - [ ] Gosh darn it, its still called /share-evidence, didn't we change that already?
  - [ ] Can you upload a picture?
  - [ ] Can you upload a *second* picture?
- [ ] /officer-details
  - [ ] Can you enter all information about 2 officers?
- [ ] /witness-details
  - [ ] Can you enter all information about 2 witnesses?
- [ ] /about-you
  - [ ] Can you enter all information about 1 yourself?
  - [ ] Maybe do like 1 or 2 runs (out of the 4 forms) where you don't enter your information here, but wait until the final email submission form to see if that works.
- [ ] /review-and-submit
  - [ ] Is all your information there?
- [ ] /confirmation
  - [ ] See if that email input thing works for the runs where you didn't enter personal information.
- [ ] Check your email
  - [ ] Did you get an email with your confirmation number?
  - [ ] Does the copy of your report have all the stuff you entered in it?
  - [ ] If not, double check with Sergio, because I think he's still getting all of our staging emails.
- [ ] Modal
  - [ ] Does the modal pop up when you try to switch languages when you've entered data?
  - [ ] Does it let you switch to another language if you say "Yes"?
- [ ] Spanish Form Considerations
  - [ ] Is it in Spanish? (Did all of our text translations work?)

Sprint-specific considerations to kinda watch out for:
- [ ] https://github.com/cityofaustin/techstack/issues/1644
  - Covered by regression testing. Basically make sure the map on /where-happened works when you enter an address.
- [ ] https://github.com/cityofaustin/techstack/issues/1743
  - Covered by regression testing. Basically make sure the file uploader on /share-evidence works.
- [ ] https://github.com/cityofaustin/techstack/issues/1086
  - Covered by regression testing. Basically make sure the datepicker on /what-happened works.
- [ ] https://github.com/cityofaustin/techstack/issues/1591
  - Covered by regression testing. Basically make sure the calender icon selector thing still works on /what-happened.
- [ ] https://github.com/cityofaustin/techstack/issues/1579
  - Covered by regression testing. Basically make sure that location is still required on /where-happened even if you clear out your location.
