### ISSUE TITLE
Copy-not-code updates to OPO confirmation emails

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1825]
Review criteria: 
- [x] On Thank You confirmation email, English subject and heading should be `Your thank you was submitted successfully!` [#1783](https://app.zenhub.com/workspaces/office-of-design-and-delivery-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/1783)
- [x] On Thank You confirmation email, Spanish subject and heading should be `¡Su nota de agradecimiento fue enviada!` [#1783](https://app.zenhub.com/workspaces/office-of-design-and-delivery-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/1783)
- [x] Spanish confirmation email subject and heading should be `Su queja ha sido enviado.` [#1779](https://app.zenhub.com/workspaces/office-of-design-and-delivery-5a78b88e1ce69f3510b678ef/issues/cityofaustin/techstack/1779)
- [x] On confirmation email, "sexo" should be `hombre` and `mujer` (not "masculino" or "femenino") [#1813](https://github.com/cityofaustin/techstack/issues/1813)

**Comment by desigonz** [comment]
Changes live in [PR 24](https://github.com/cityofaustin/form-service-api/pull/24). Assigning to @sergiogcx to review.

**Comment by sergiogcx** [comment]
Looks good, one small adjustment and it's good to go. Feel free to merge to master.

**Comment by desigonz** [comment]
@sergiogcx Thanks! Merged and closing now.
