### ISSUE TITLE
Make Guide in joplin; new page type

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#1851]
Authors can collect a set of pages into a guide with sections in order to organize existing content in a structure that's more easily understood

This issue covers the UI within wagtail and how authors:
- [ ] Add a title for the guide
- [ ] Add a description for the guide (probably used on TC pages)
- [ ] Create sections headers
- [ ] Add links (to existing pages) and order them within sections
- [ ] Assign the guide to a TC

**Comment by easherma** [comment]
From talking with the content team, my understanding is that we are actually going to migrate the process page to the guide page.
