### ISSUE TITLE
Review all existing alpha content

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1855]
Review all content. Make sure to check for:
- [ ] [service-oriented language](https://austin-gov.gitbook.io/digital-style-guide/write-with-service-oriented-language) 
- [ ] using the correct titling conventions
- [ ] general proofreading (spelling, grammar, punctualization, capitalization)
- [ ] [Fact check](https://docs.google.com/document/d/1yL3afGS_72aFYBoF7ZH90yUCNeqAgYx1RuRxc_JbZAw/edit#heading=h.aly1tfof6fg3)
- [ ] complies with our [editorial style](https://docs.google.com/document/d/1yL3afGS_72aFYBoF7ZH90yUCNeqAgYx1RuRxc_JbZAw/edit?usp=sharing) (are all headings sentence case? Are we formatting phone numbers address consistently? etc etc) 

Make sure to review:
- [ ] page content
- [ ] contact info
- [ ] hours

**Comment by desigonz** [comment]
dupe of a bunch of issues I made yesterday
