### ISSUE TITLE
Initial Austin.gov roadmap

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#205]
_A product roadmap is a high-level visual summary that maps out the vision and direction of your product offering over time. A product roadmap communicates the why and what behind what you're building. It's a guiding strategic document as well as a plan for executing the strategy._ 

We need a living product roadmap that presents the vision and direction for Austin.gov. It should communicate both the why and what behind what behind the features we build and resources we create. It will help guide strategy and communicate with the community. 

- [x] [Initial draft](https://docs.google.com/spreadsheets/d/1jcAka1Gf3xK2utzWTsEey7TiKVRcj_iVBaV026FxySs/edit#gid=0). _Created by the core team 2/18_.
- [x] Add additional backlog features to medium- and long-term.
- [x] Draft mission and vision. _Informed by [Digital Service Values](https://docs.google.com/document/d/1KCsfOMmbM8fz0AN3BVvNAHLpo2Klh2H8RueHwup0LWM/edit?usp=drive_web&ouid=109109021747362399747)_.
- [x] Core team feedback and review. 
- [x] Create visual representation. 

[Examples](https://docs.google.com/spreadsheets/d/1jcAka1Gf3xK2utzWTsEey7TiKVRcj_iVBaV026FxySs/edit#gid=0) 

[High Level Road Map](https://docs.google.com/presentation/d/1nRdIYPgzVc8Rh2VCR8jIYPfKRm4sO1g6JTbg2ZHKJuc/edit#slide=id.g38ce77a6e6_0_0)

**Comment by amenity** [comment]
@cthibaultatx - would you please upload a photo of your notes from our meeting yesterday?

**Comment by cthibaultatx** [comment]
![img_9565](https://user-images.githubusercontent.com/20911665/37832106-9920e97e-2e75-11e8-9934-b743d8a5a50e.JPG)
you got it! @amenity

**Comment by cthibaultatx** [comment]
If I can make a suggestion after looking at your notes above, I think the next step after drafting statements is to create the visual representation then gather feedback. It can be a rough prototype and the process could start by thinking about the different ways everyone in the office perceives information: project board, google document, github issue, slack, notes. Then figure out a visualization tool/location/format that works for all and mock up your map there.

**Comment by amenity** [comment]
https://docs.google.com/presentation/d/1GGA9qnDPpDyS8zk2annOBXsdo6gm2S5FI6-67ukEe-U/edit#slide=id.g41638224bd_0_197
