### ISSUE TITLE
Janis Joplin post-hustle next steps

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/techstack#207]
Prioritized List:
- [x] create a new spreadsheet for missing translations @cthibaultatx  (logged #211)
- [x] plug in missing content
- [x] Arabic translation RtL for usability testing on Saturday @mateoclarke 
- [x] Fix the language select in LanguageSelect @ifsimicoded 
- moving themes (& topics) into query and getting them into janis @mateoclarke 
   - [x] use slugs instead of IDs
   - [ ] Theme Pages #98 
   - [x] Topic Pages #92 
- [x] Fix phone numbers in contact module
- [x] remove United States @mateoclarke 
- [x] replace location title: Recycle & Reuse Drop-off Center (cityofaustin/joplin#102)
- [x] bulk-item-pickup nested list should NOT be in a new step -- the markup should look
`<li><p>Step 5 content here </p><ul><li>nested list content here<li> ... </ul></li>` @benweatherman
- [x] Make menu full height https://github.com/cityofaustin/janis/issues/176 @ifsimicoded
