### ISSUE TITLE
Add missing translated Spanish content

### ISSUE THREAD

**Issue by cthibaultatx** [cityofaustin/techstack#217]
Translated content file: https://docs.google.com/spreadsheets/d/1HN3NGcSWajZ3wbTmUtc01X4MOirimzVsAjPp2DKYWDU/edit?usp=sharing

### Navigation
- [ ] Replace "Housing & Utilities" in breadcrumbs with "Vivienda y servicios públicos"
- [ ] Replace "Recycling, trash, and compost" submenu item with "Reciclaje, basura y compostaje"

### Look up your trash, recycling, and compost pickup days
- [ ] Add jump link to "Ingrese su dirección en la siguiente casilla" in first line of step #1 to scroll down to app

### Drop off household hazardous waste
- [ ] Add jump link to "Use la función “What do I do with”" in first line of step #1 to scroll down to app
- [ ] add jump link to "lo que debe y no debe hacer con los desechos peligrosos del hogar" in step #2 to scroll down to H2 of supporting service content, "¿QUÉ MÁS NECESITO SABER?"

### Get ready for curbside bulk item pickup
- [ ] Add jump link to "Use la función “What do I do with”" in first line of step #1 to scroll down to app
- [ ] Add jump link to "My Collection Schedule" to scroll down to app
- [ ] Add jump link to "lo que debe y no debe hacer con los artículos grandes" to scroll down to H2 of supporting service content, "¿QUÉ MÁS NECESITO SABER?"

### Pick up free paint
- [ ] Make "*El mantillo orgánico lo tiene que empacar usted mismo. Traiga una horqueta o pala, guantes de trabajo y recipientes." one paragraph vs. 2 separate lines. Reference English version if needed.
- [ ] @ashleecoa @LauraTrujillo @courtneyjacinic the last paragraph of this service's supporting content is missing from the translated word doc: "Need to drop off items to be recycled? See how to drop off at the Recycle and ReUse Center." Not sure if it's missing from any others.

### Get ready for curbside compost
- [ ] Add jump link to: "la función “What do I do with"" in step #2 to scroll down to app

**Comment by ashleecoa** [comment]
Moved to #211
