### ISSUE TITLE
Wagtail show-and-tell

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2372]
**Objective** 
For the features/enhancements we're currently designing, we want to understand what Wagtail can do, and then we can make the decision to not use Wagtail's solutions if they don't serve our/our users' needs.

**Participants**
@toribr 
@chasechenevert 
@briaguya 
@desigonz 
@easherma 

**Agenda**
Dev team, this is the list of things we're interested in exploring in Wagtail:
- [x] Search page and filters (related to #2349)
- [x] Assigning pages to IA and creating new topics (#2223)
- [x] Batch publish/unpublish (#2268)
- [x] WYSIWYG field design and placeholder text (#2368)
- [x] Does Wagtail behave differently at certain breakpoints?

------
- [x] Schedule meeting **this will tentatively take place at the end of dev/design sync on 6/25**
- [x] Meet
- [ ] Create resulting issues

**Comment by easherma** [comment]
FYI https://control.divio.com/demo/get-new/wagtail/ looks like a pretty easy way to spin up a version of the wagtail demo site

**Comment by easherma** [comment]
> Does Wagtail behave differently at certain breakpoints?

Yes, it does. The default wagtail admin is decently mobile friendly. Our version of admin definitely is not.

**Comment by toribr** [comment]
FYI @easherma that demo is useless for our purposes - we're more interested in understanding what wagtail means by "Super-powerful hierarchical content management ("content trees").

**Comment by desigonz** [comment]
If you click on the little bird icon in the bottom right corner, you can access the backend. The hierarchy uses a file-folder structure, which doesn't really help with the whole polyhierarchy business. 
![image](https://user-images.githubusercontent.com/5839508/59777720-c62cc900-927a-11e9-8aa3-97f4cc06e602.png)

**Comment by toribr** [comment]
Oh yeah, duh. But also a good demonstration of why graphics shouldn't be used as buttons.

**Comment by desigonz** [comment]
It also times out after 15 minutes 🙄
@easherma offered/threatened to stand up a version of Wagtail on Heroku that we can play around with.

**Comment by desigonz** [comment]
and voilà!
https://oddwagtailbakery.herokuapp.com/
login: admin, pw: changeme (but don't change it)
eternal grateful to @easherma
