### ISSUE TITLE
Update design documentation

### ISSUE THREAD

**Issue by chasechenevert** [cityofaustin/techstack#2597]
# Janis 2.0 design documentation
It has been awhile since documentation has been updated, so let's refresh documentation with a focus on sharing for non-designers.

- [ ] Update documentation across: styles, components, page templates
- [ ] Update purpose and principles
- [ ] Decide where this information should be shared. Gitbooks, XD, Docs, Slides?

**Dev spec updates**
- [x] add a landing page 
- [ ] add documentation notes into the XD document
- [x] overhaul display of components, styles, etc. using janis elements but don't recreate alpha
- [x] add navigational structure so that users can navigate the spec

**Comment by desigonz** [comment]
<3 this issue

**Comment by chasechenevert** [comment]
Closing this issue out in favor of smaller, discrete meetings and tasks in the hopes of getting the tires out of the mud. Just an idea of what I'd like to be able to cover under the umbrella of a Design System (issues to create for the backlog).

- **Goals for our design system** plenty of good reasons to create a design system, but what are our goals: ship faster, ensure consistency, wide application (etc.)? What do devs want/need? 
- **Product/design principles** shared guidelines that capture the essence of what good design means for the team and product, and advice on how to achieve it. This should be informed by all disciplines. Examples: [gov.uk ](https://www.gov.uk/guidance/government-design-principles), [Altassian](https://www.atlassian.design/guidelines/designPrinciples/design-principles), [USWDS](https://designsystem.digital.gov/about/design-principles/).
- **Glossary** for consistency in names of components (example are "cards" and "tiles" the same thing?). 
- **Interface inventory** organize UI elements based on styles. The goal can be to identify inconsistencies in UX or visual design, or to define essential patterns.
- **Purpose-directed interface inventory** organize UI elements based on purpose or user behavior/goal. The goal is to define the most essential design patterns and get mutual understanding on how they should work across the system. 
- **Content type/component audit** list the range of content types and components that alpha will eventually need (things like alerts, events, login, etc. a lot of this might be in the backlog, come from the content audit that's in progress for austintexas.gov) so that we can inform _what_ the patterns are that we can standardize into the design system.

**Comment by chasechenevert** [comment]
Stale re: Abstract, will create a new issue.
