### ISSUE TITLE
Managing large numbers of official documents

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2668]
### As a content editor adding official documents, I want an easy and understandable way to manage many document entries within the official document content type.

**Acceptance criteria**
~~- [ ] (a) Empty instance as first instance upon page load (pretty hard)~~
- [ ] (b) Documents listed in reverse chronological order (pretty hard)
- [ ] (c) Remove implied ability to re-order (easy)
~~- [ ] (d) Show each *past* doc collapsed to date to improve findability (I'm flexible on what this actually looks like) (pretty easy, but controlling field that shows up might be harder)~~
- [ ] (e) Rendered date should be month-date-year 

Note [tori]: Some items made obsolete by updates to official doc and official doc container #4504 

![#2668](https://user-images.githubusercontent.com/3790067/64995571-33afbc00-d8a1-11e9-96c5-d5fdb809ff6a.png)

### Background
In #2572, we implemented the MVP for official documents.

**Comment by toribr** [comment]
@easherma & @briaguya have a pattern they found out about during wagtail space that allows collapse components. Should be a matter of defining interaction details.

**Comment by easherma** [comment]
See http://docs.wagtail.io/en/v2.0/reference/pages/panels.html#multifieldpanel

**Comment by toribr** [comment]
![#2668](https://user-images.githubusercontent.com/3790067/64995571-33afbc00-d8a1-11e9-96c5-d5fdb809ff6a.png)
Requirements:
-[ ] (a) Empty instance as first instance upon page load
-[ ] (b) Documents listed in reverse chronological order
-[ ] (c) Remove implied ability to re-order
-[ ] (d) Show each *past* doc collapsed to date to improve findability (I'm flexible on what this actually looks like)
-[ ] (e) Rendered date should be month-date-year

**Comment by easherma** [comment]
Making them collapsible is easy; making the title of the collapsible area dynamically be the rendered date is going to be harder.

**Comment by desigonz** [comment]
assigning to myself to split up into multiple issues

**Comment by desigonz** [comment]
Split these into issues #3177, #3178, and #3179

**Comment by toribr** [comment]
Revisit this issue post bi-directional and updated official docs (July)
