### ISSUE TITLE
Joplin MVP translation model

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2670]
### As a content editor, I want translations in Joplin to be consistent so that I'm not confused about how to enter translations.

**Acceptance criteria**
- [ ] @toribr identifies all the areas where we need to clean up the Joplin translation model for MVP
- [ ] @desigonz works with design team to develop acceptance criteria

**Is your feature request related to a problem? Please describe.**
Entering translations in Joplin can be inconsistent. Sometimes it's by using the language tab at the top of the page; other times, like on department pages, it's through the streamfield.

![image](https://user-images.githubusercontent.com/5839508/62310915-33be3e80-b450-11e9-9a77-758cf154608f.png)

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/2b1ecdb3-5eef-4447-8310-e99232ca14f3)

![image.png](https://images.zenhubusercontent.com/5a31a50b8a75884b908b0ea6/f0b0a281-d238-4a44-9888-02f6f1809036)

![image](https://user-images.githubusercontent.com/5839508/63073827-1d07f500-bef0-11e9-9407-655aa9a770fe.png)

**Describe the solution you'd like**
Translations should only be managed via one method—the tabs at the top.

**Describe alternatives you've considered**
*A clear and concise description of any alternative solutions or features you've considered.*

**Additional context**
*Add any other context or screenshots about the feature request here.*

**Comment by toribr** [comment]
Examples of additional instances where variation occurs:
Add Department Director
![Screen Shot 2019-08-01 at 12 03 45 PM](https://user-images.githubusercontent.com/3790067/62312690-77b34280-b454-11e9-84be-a8432b161693.png)
Maps:
![Screen Shot 2019-08-01 at 12 05 57 PM](https://user-images.githubusercontent.com/3790067/62312837-d5478f00-b454-11e9-92b3-f2635a56a4a6.png)

**Comment by toribr** [comment]
https://github.com/cityofaustin/techstack/issues/2193
Character limit per language may also need to be considered for this issue.

**Comment by toribr** [comment]
Solutions are predicated on content authors entering data from another document, since we know translators prefer their own tools. Assumptions I'm making about this flow with regards to UI:
- [ ] All translations for any particular page should be viewable on that page. Ie, no translations should be embedded in streamfield or within snippets.
- [ ] Non-translatable fields should be present but not editable, ie, location names. This will help the author keep track of where they are in the document.
- [ ] Alternate language pages should be identical replicas of the english version by default. Ie, authors should not have to re-create a page for another language.

Additionally, tracking translations presents an even greater challenge:
- [ ] There may need to be some sort of notification mechanism for when english pages are updated, but not their non-english counterparts.
- [ ] There may need to be some overview which allows an author to see which pages have been translated into other languages
- [ ] There may need to be some mechanism by which authors manually notify the system that updates to translations are needed. I'm thinking that an author may make changes which update the "last updated" date, but which don't in fact necessitate a translation update.

**Comment by easherma** [comment]
@desigonz feel free to split this into a separate issue for the tech side if that makes sense

It's clear that the current model for translations is not sustainable or desirable UX. Wagtailtrans has been identified as a potentially tool for managing translations as a multi-site setup as opposed to per model. 

https://wagtailtrans.readthedocs.io/en/latest/index.html

It looks like regardless of what tools we use, we need to consider the criteria Tori lists above. Wagtailtrans seems to have a good system in place for keeping changes synced. It might take a good amount of custom code to make the notifications described happen, but the foundation would be there. Migrating existing translated content might be a pain, though that means we ought to nail down a good system sooner rather than later.

**Comment by desigonz** [comment]
@toribr, thanks for your great thinking/work on this! I created issue #2744 in which I've outlined acceptance criteria for the short-term clean up in Joplin 2, and split out what strikes me as things to solve in Joplin 3.0 once we rebuild translations. I also added a few questions for you in the acceptance criteria. Let me know what you think; we also should review at dev/design sync next week.
