### ISSUE TITLE
Revise pages with appblocks

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2673]
In #2666, we now have the ability to add apps like Trashy and ReCollect between steps. 

Let's review and rewrite the following pages to incorporate the apps within steps:
- [Bulk item pick up service page](https://alpha.austin.gov/en/housing-utilities/recycling-trash-and-compost/household-waste/bulk-item-pickup)
 - [Get ready for compost pickup service page](https://alpha.austin.gov/en/housing-utilities/recycling-trash-and-compost/household-waste/compost-pickup)
- [Drop off hazardous waste service page](https://alpha.austin.gov/en/housing-utilities/recycling-trash-and-compost/household-waste/hazardous-waste-dropoff)
- [Look up trash days service page](https://alpha.austin.gov/en/housing-utilities/recycling-trash-and-compost/household-waste/trash-recycling-pickup)

------

### background

This page needs some revising: https://alpha.austin.gov/en/housing-utilities/recycling-trash-and-compost/household-waste/trash-recycling-pickup
- [ ] It's a service page with no steps!
- [ ] There's mention of signing up for text, email, or phone call reminders and alerts in the description, but no body content pointing to it
- [x] Let's do something about the double "type your street address" headings
- [ ] Whatever changes we make, we need to update the Spanish translation as well.

![image](https://user-images.githubusercontent.com/5839508/62328921-0d14fd80-b47a-11e9-9978-1187999e947f.png)
