### ISSUE TITLE
Roadmap iterations

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2722]
- [x] get a paid account
- [ ] share with the team
- [x] add more to the roadmap

**Comment by desigonz** [comment]
We now have an austin.gov roadmap (which is always a work in progress :wink:) that you can view!

To do so, go to http://bit.ly/odd-roadmap and then login using the odd@austintexas.gov credentials. The credentials are logged in 1Password. If you don't have a 1Password account, work with @oliver2g to get it set up.
