### ISSUE TITLE
Draft content for disciplinary memos

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2725]
This is an epic for drafting content for all of the OPO disciplinary memos published since November 15, 2018: http://www.austintexas.gov/department/disciplinary-memos + additional ones that OPO needs to share to us

- [x] get additional docs from OPO
- [x] first draft of this content by end of sprint 38 (should be ~10 memos)

**Comment by desigonz** [comment]
@srigdon Feel free to make batch memos as issues within this epic if that helps you track progress (or create a checklist here?)

**Comment by srigdon** [comment]
- [x] Draft content for the published memos (the ones that are already on austintexas.gov).

**Comment by srigdon** [comment]
- [ ] Draft content for the remaining four memos, and edit the descriptions for all memos to include one sentence about the officer's actions.

**Comment by desigonz** [comment]
Yay closing this one!
