### ISSUE TITLE
Design a picker page that's contextual and easier to use

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#2746]
We're using picker pages for a number of tasks across page types, but the picker isn't very smart. Also, it shows content details that may or may not be useful to the task at hand. Let's refine these pages to work better for each task and instill some consistency while we're at it. And add search, which in some cases will be necessary for some tasks.

**Comment by toribr** [comment]
Used in four places
- [ ] Selecting a dept from many page types
- [ ] Selecting an existing page from guide type
- [ ] Selecting a topic from many page types
- [ ] Selecting a related department from many page types

![image](https://user-images.githubusercontent.com/3790067/63108637-f9bf6300-bf4c-11e9-859f-56f307cc265f.png)

**Comment by toribr** [comment]
Elements that need to be configured per picker:
-[ ] content type allowed
-[ ] status of allowed content types (live and live + draft or draft)
-[ ] contextual alert message
-[ ] search box or not

**Comment by desigonz** [comment]
@toribr developing acceptance criteria now. Has content reviewed the microcopy?

**Comment by desigonz** [comment]
Okay acceptance criteria lives here! https://github.com/cityofaustin/techstack/issues/2855 @toribr  Thanks for your great notes/mocks.

@srigdon I believe you reviewed the microcopy? I think we need a period with the search result copy ("There are x matches." where x is the number of search results)

Additionally, the mocks indicate that top services can be info, service, guides, and official docs. Is that true? We might want to take a look at that later once they're publishing side-by-side—would it be weird to see different title conventions treated the same way, side-by-side? Is some content more important than others and should be reserved for "top services"?

**Comment by toribr** [comment]
@desigonz 
Full disclosure: I made the change to include official docs, because it is easy to imagine that OPO will want to prioritize their memos, and from there it's also easy to imagine that some depts will have similar content. Also - it's easier to test if we allow it than if we prohibit it. So my thought was to include it and then we can see how it goes.

**Comment by desigonz** [comment]
Okay interesting, and thank you!
