### ISSUE TITLE
Interface inventory activity

### ISSUE THREAD

**Issue by chase-vert** [cityofaustin/techstack#2836]
# Interface inventory activity for Janis and Joplin

**Goal**
We will leave this working session with an understanding of the patterns throughout our interfaces and how we're connecting those patterns to the greater whole of the system. Ideally we should perform these audits regularly to ensure we're scaling our work sustainably. 

**Background**
Lots of big and small decisions have been made over the past year but we haven't really ever taken a step back to evaluate the whole product.

## To-do
- [x] Print 3 copies of each page
- [ ] Cut out sections based on their component or function (headings, body, contact, footer, etc.). Leave one set of copies intact for comparison.
- [ ] Group based on criteria. Purpose, and style are examples, but we can group based on anything we need clarity on.
- [ ] Document learnings. Do we need to make any adjustments based on the exercise? Have we discovered or clarified any patterns?

**Comment by chase-vert** [comment]
Closing this since Abstract takes care of this.
