### ISSUE TITLE
Glossary rough draft 1

### ISSUE THREAD

**Issue by chase-vert** [cityofaustin/techstack#2837]
# Glossary of terms

**Goal**
Record the terms we use to discover inconsistencies, and note where we might need to change terms to create clarity. This activity will likely require follow-up and feedback on the team to reach consensus. 

## To-do
- [ ] record existing component and content type names in this spreadsheet: [Janis 2_visual design audit](https://docs.google.com/spreadsheets/d/1aSeJhXNhECYmyU4NWxGGlE_Z4Ou5OfIM2mpNSPC6IcA/edit#gid=1622579261)
- [ ] indicate where there are discrepancies in names
- [ ] update terms across XD spec for parity
- [ ] display terms on pin-up boards
- [ ] schedule follow-up or pass-off as necessary

**Comment by chase-vert** [comment]
This is happening via Abstract
