### ISSUE TITLE
Design principles rough draft 1

### ISSUE THREAD

**Issue by chasechenevert** [cityofaustin/techstack#2839]
# Design principles draft 1

**Goal**
Develop a rough draft of 3-5 design principles to ground the design team's work, and ensure that we're manifesting the purpose of the product through the design. This work will certainly need to be informed by the wider team, but a small group of us can hammer out some ideas that we can build on. I'm envisioning this as a working exercise. 

**Background**
Our office has [a great set of principles](https://odd.austintexas.io/how-we-work/) that summarize who we are and how we work. We haven't ever developed any guiding principles for our design work partly because it had been premature to do so. Nearly one year in Janis looks completely different, and we've added a number of components and content types. As we set out to develop more content types, features, and complexity, it's a good time to wrap principles around our work to help us align, and move faster.

**Examples**
[gov.uk ](https://www.gov.uk/guidance/government-design-principles), [Altassian](https://www.atlassian.design/guidelines/designPrinciples/design-principles), [USWDS](https://designsystem.digital.gov/about/design-principles/).

> Vague: "Make it clear."
> Practical: "Only one number 1 priority. What do you want your users to see and do first?"
> 
> Vague: "Make it simple."
> Practical: "Make it unbreakable. Just like a children's toy, make sure it was designed for exploration and impossible to mis-tap."
> 
> Vague: "Make it useful"
> Practical: "Start with needs. If you don't know what the users needs are, you won't build the right thing. Do research, analyze data, talk to users. Don't make assumptions."

## To-do
- [ ] gather a small group (could be during pin-up, or an additional meeting)
- [ ] have the group answer questions like: "what does good design mean to Alpha? For residents? For city staff?", "what matters most?" etc. refer to the above examples. 
- [ ] group stickies, and select 3-5 as our rough draft
- [ ] by the end of this exercise, we should be able to draft a 4-5 sentence summary of our design approach via principles

**Comment by chasechenevert** [comment]
Here's draft 1! 
https://docs.google.com/document/d/1fqqs7ml0WIp5TCau9kdmQvdm8QpbjndnnSSkoO7If0I/edit#
