### ISSUE TITLE
Send APH the rest of the content

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2852]
Environmental Health, Health Equity, and Epidemiology content.

**Comment by desigonz** [comment]
@Jo-Dwyer Here's the content I've compiled that's ready to go to APH. Ready for you to do your magic!

### Community services
- [ ] [Resources for healthy teens information page](https://docs.google.com/document/d/1Y1isYhlE3fSHSOkMfYO3DlGnSaCLmSlfRp-q_utt7QM/edit)
- [ ] [Breastfeeding support information page](https://docs.google.com/document/d/1khKjxBj5J8bmHz4828VthHol5NgeujYUFXzqKGDOuoY/edit)
### Epidemiology & public health preparedness
- [ ] [Crypto and other waterborne diseases information page ](https://docs.google.com/document/d/1t1LP2L6M62zDIuYAcViY4rfJ8WKX3arTobuaapLk3gs/edit)
- [ ] [Flu information page](https://docs.google.com/document/d/1qJxR_bx6cRj9To3L5ehGZt0LTAUtiLrlKvrdB7ciasI/edit)
- [ ] [Hepatitis information page](https://docs.google.com/document/d/1f35ASX3d-GRe7WOJAaU2QRyevX9rBnVj1eifmi6QW3c/edit)
- [ ] [Mosquito-borne diseases information page](https://docs.google.com/document/d/1JIssBsLRoBYkIr-LhzbWTAUTlgonOELvvIc3PrzaFC8/edit)
### Health equity and community engagement
- [ ] [Find support for pregnancy and motherhood service page](https://docs.google.com/document/d/1N6y1lJv4HfyfOcc_l6kxZXBnda3v3gGQLg7zFDWQgPU/edit)

### You're also drafting up a few new pages
- [ ] #2925 tax free/financial assistance
- [ ] #2927 free clothing and fans at neighborhood centers
- [ ] #2910 splitting fall prevention into two pages
- [ ] #2857 revising day labor

-------
### backlogging
We dug up three old drafts to review. We're going to backlog these.
- #2946 bats service page
- #2947 affordable/fresh food options service page
- #2945 report diseases service page
