### ISSUE TITLE
Implement custom React Form components for AAC Foster Form

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/techstack#287]
In order to move AAC Foster form past the prototyping phase, we've discussed moving the form into Janis. See https://github.com/cityofaustin/techstack/issues/269

Design docs here: https://drive.google.com/file/d/1nJePAA3EI1APmdFK8zcBjh4OuajyjElG/view

We should continue the work from: https://github.com/cityofaustin/janis/pull/241

## TODOS:
* [ ] Create component for "Add Additional information" textareas and add them to schema
* [ ] Create custom component for:
  * [x] `<Radio/>`
  * [ ] `<Checkbox/>` widget to fix styling issues caused by USWDS
  * [ ] plain `<Input/>` string fields
  * [ ] `<Textarea/>` string fields
  * [ ] conditional `<FormAlert/>` for use with `<Radio/>`
  * [ ] `<StreetAddress/>` that uses Google Address API for autocomplete
  * [ ] Block of fields for adding info about dogs & cats
  * [ ] Add validation to necessary fields (ie: phone number, email, etc)
  * `<PhoneNumberInput/>` and `<EmailInput/>` to help with standardized validation
* [ ] style "description" text for all components
* [ ] update styling of progress bar component
* [ ] Add `required` to needed fields
https://github.com/cityofaustin/techstack/issues/364
* [ ] Refactor Form code that enables `condition` in uiSchema to be more reusable. As a HOC? or new Form class component?
* [ ] Use Router to update url path on page stepping bc @ifsimicoded said so.

Aha! Link: https://desi1.aha.io/features/RT-323

**Comment by cthibaultatx** [comment]
Hi! Julia handed off final form refinements to me and @toribr Friday May 11. Things that have been updated/done since then:
- annotated 1 mobile mock up in sketch file
- eliminated confirmation modal to remove form data
- Removed "x" from the right of the field when in error state and looking for another, non-color element (maybe dotted line border) to point people to the field with the error who may not see red.


Requests from Julia and team:
- Match form field widths to content width
-- example: Every field in the form should have its own line but fields for phone numbers, for instance, should only be as wide as a standard 9 digit number requires. (international # implications?)
- Use google API to recommend address to resident as they fill out street address
- Validation happens on blur

Sketch file: https://drive.google.com/open?id=1648ltRiihC2G6vVPyfSWiyXP_2qXkuNV

**Comment by cthibaultatx** [comment]
One big difference that is not currently accounted for in Janis is using san-serif for body. We are moving to have a serif and san-serif body. I'll attach the styles here momentarily.

**Comment by mateoclarke** [comment]
Thanks @cthibaultatx. I've been researching, exploring and experimenting with forms helper libraries and frameworks within the React ecosystem. I've also been experimenting with the right pattern to manage state in multi-step forms. Since each step isn't its own page in a Single Page App (SPA), we have to manage that stepping process as component state. You can see my code and a summary explanation about what I learned in this PR: https://github.com/cityofaustin/janis/pull/235

The long story short is that I've narrowed down which library I'd like to use to implement the form, `react-jsonschema-form`. I'm aware of at least one potential obstacle, triggering events `onBlur` (when a user moves from one field to the next) instead of `onSubmit` (when a user clicks the Next Button) or `onChange` (when any state change happens within a field aka: live validation). I'm going to email some VA contacts for advice on that.

Now, I'm starting to build react components for each type of input field so that we can reuse them throughout the form schema. Here's an example, `<RadioWithConditionalMessage/>`: https://github.com/cityofaustin/janis/pull/235/files#diff-dd686e1fff7c11189e14504b47e3b26b. I'll start implementing them with the styling and UX you're describing and I'm sure I'll have questions.

**Comment by cthibaultatx** [comment]
Pulling @toribr in since we're both working Julia's form.

Is it easier to build with what they have then we can review IF we should change any of the elements? Then determine how?

Also, if onBlur is not an option out of the box then I think @toribr and I agree on onSubmit.

**Comment by mateoclarke** [comment]
As we discussed in a Slack DM, syncing up and reviewing the standard implementation ASAP sounds good. Let's plan to meet at Faulk tomorrow with an option to screenshare via Hangout. We may want to do a more in-depth design pin-up next week too.

**Comment by toribr** [comment]
To clarify, it's the multi-page form that is making it harder to implement onBlur? Because onSubmit is a terrible user experience if more than 1 field has an error.

**Comment by mateoclarke** [comment]
No multi-page @toribr and onBlur are separate issues. I have a warm lead on how to add onBlur.

**Comment by mateoclarke** [comment]
Updated the description above with next steps from https://github.com/cityofaustin/janis/pull/241
