### ISSUE TITLE
Guide Page QA Test Plan

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#2884]
Desktop Criteria:
- [x] UI Implementation matches design. Does the site look like the mocks? https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/58cef195-a92f-450c-ba2e-4124f44b9469/Template-Guide-desktop/
- [ ] Sidebar is sticky. When you scroll down to reach it, it should stay stuck.
- [ ] When you move to different sections, the sidebar will highlight the correct section you're on.
- [x] Clicking on a section in the sidebar will take you to that section.
- [ ] Breakpoints for responsive design:
  - [ ] over 480px up to 767px is mobile
  - [ ] over 768px up to 1079px is tablet
  - [ ] over 1080px is desktop

Mobile and Tablet Criteria:
- [ ] Mobile UI Implementation matches design. https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/a5132472-47f7-4fa1-ba90-223af090026f/Template-Guide-mobile-1/
- [ ] Tablet UI Implementation matches design. https://xd.adobe.com/spec/3693e3d0-1e3d-4c07-6555-b09fccd75568-40a2/screen/0c710da7-eff9-4a62-b3bf-8b5adeec771e/Template-Guide-tablet/
- [x] Clicking the "Table of Contents" open the menu.
  - [x] The background freezes and doesn't scroll.
  - [x] The menu will highlight the the correct section you're on.
  - [x] Clicking on a section in the menu will take you to that section.
  - [x] Clicking on the background/Menu bar will then close the "Table of Contents" menu

**Comment by desigonz** [comment]
Thanks @Niicck for your test plan! Making this one an epic. I incorporated details above into issues filed within this epic and assigned to @anukandimalla.
