### ISSUE TITLE
Location content type

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2966]
### As a resident, I want information about a City building or site such as location, parking, services offered, and accessibility info, so that can easily navigate to services I need.

**Additional context**
[Places research](https://docs.google.com/document/d/1gHhYiFrPaNYJQf_j9qiSqJGVe7Nks-TurbQkmD8TdNs/edit#)
More background in #2364

**Comment by desigonz** [comment]
> Two ways of creating custom maps via Google:
> 1. My Maps: https://www.google.com/maps/d/?hl=en. User can customize things and add collaborators, but the list doesn’t include all of the information that “Your places” feature in Google Maps displays. Includes a link to “View in Google maps”, but no link to the city of Austin page.
> 2. Your places feature in Google Maps, example: https://goo.gl/maps/Z39GZeAJbmHXjvup9. Can’t add collaborators, but results are more detailed than My Maps.

**Comment by desigonz** [comment]
Objectives:
- As an resident, I want to be able to easily view where I can obtain a service
- As a resident, I want to be able to see details about a location's accessibility, hours, parking, and other issues which may effect my ability to obtain a service.

Artifacts:
- [ ] Comps using real-world service content for single "places" page
- [ ] Comp using real-world content for mulitple location places page
- [ ] Comp for how contact snippet and places work together
- [ ] Comp for department place page

**Comment by desigonz** [comment]
From @chasechenevert:

> We determined that for MVP we'll just focus on creating the individual Place pages, and link to them where locations are currently listed within service pages (or elsewhere).
> 
> Place page: includes all information that the contact snippet has including: phone numbers, fax, email, hours

**Comment by easherma** [comment]
Copying over some relevant questions: 

- do we need a separate element for fax or could we just use the existing phone snippet with the description as 'Fax'
- How will the data differ from contact snippets? Or as a content type will it primarily look like an aggregation of snippet data ( in either case, we just need to add a geocoded lat/lng to the data we pass along to Janis )
-  if we want the language to be mostly standardized on the places content type (for stuff like accessibility, appointments, etc), it makes more sense to implement a Model and use Wagtail's ModelAdmin(basically a more complicated snippet that we can make our own admin interface for editing) to manage this data rather than a page. That way an author could just select a checkbox and Janis would know to attach the proper copy or something like that.
