### ISSUE TITLE
Dev/design sync 9/17/19

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2971]
## Issues to review 📝

- [x] Guide
  - [x] #2962 guide—smooth anchor links 
- [x] Publishing out footer links like the privacy page
  - [x] #2862 URL structure for pages global to the whole site
  - [x] #2996  
  - [x] #2948 dark footer
- [x] #2997  
- [x] Document hosting (Let's take a look at issues in epic #2964)
- [ ] #2872 View live immediately after publishing (see [these mocks](https://github.com/cityofaustin/techstack/issues/2872#issuecomment-531976395))
- [x] #2978 Janis theme for forms

If we have time...
- [ ] Let’s review the rest of sprint 40 dev issues and see if we have any questions.

## Looking ahead 👀
If we have time...
- [ ] #2929 non-translatable fields
- [ ] #2931 Snippet translations
- [ ] #2581 Joplin main page mock (let’s review the acceptance criteria)
- [ ] #2668 managing large numbers of official documents
- [ ] #2368 Department placeholder text (options are to either remove requirements or keep the auto populate)
- [ ] #2747 Remove “edit page” from page pickers
- [ ] #2911 Remove ability to reorder official docs
