### ISSUE TITLE
Dev-design sync 9/30

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3023]
### candidate priorities for next sprint
- More PR branch publishing (1/2 sprint)
- P3 bugs
  - ~~Make it so timeouts don't break builds (#3047)~~
  - URL when navigating from TC to topic #3037 
  - Button not surviving "save as draft" #3029
- Snippet translations
- More document uploads (#2991, #2998) 
- Guides
  - navigating to guides?
  - heading levels in guides #3049
- Feedback module on Janis #1840
- Bunch of Janis improvements?

Quick queries?

### Guides
- [ ] #3049 Heading levels in guides

### Janis
- [x] Feedback module on Janis #1840
- [x] #2843 contextual nav style. From Brian: "can close it based on chase's comment but let's confirm in sync"

### Janis/Joplin things
- [x] #2931 Snippet translations. In order to deliver designs, we need dev team's help on even conceptualizing how translations would/should work for the rare instances (specified in the acceptance criteria) in which we need translation. 
- [x] #3029 Button not surviving "save as draft" in Joplin (aka buttons not working :( )

### Strictly Joplin UX improvements
- [x] #2368 Department placeholder text (options are to either remove requirements or keep the auto populate—need Tori to review)
- [x] #2668 managing large numbers of official documents (Joplin). We have designs as we'd like them to work, but what technical limitations do y'all see?
- [ ] #2581 Joplin main page mock. 
  - When you sort a column, the page reloads to our listing page, not the search page. That's problematic from a UX perspective. 
  - Let's review acceptance criteria in general.
- [ ] #2929 non-translatable fields. With Brian's POC, how would the dev team size this now? And do you need anymore acceptance criteria from us?

**Comment by briaguya** [comment]
not sure where this fits but we have https://github.com/cityofaustin/techstack/issues/2948 in "on deck" but it's blocked by https://github.com/cityofaustin/techstack/issues/2950 which really should include https://github.com/cityofaustin/techstack/issues/1891 so we're looking at a giant chunk of stuff here. This could use some thinking/talking about.

**Comment by briaguya** [comment]
sounds like we should talk about this one (https://github.com/cityofaustin/techstack/issues/2843), probably can close it based on chase's comment but let's confirm in sync

**Comment by desigonz** [comment]
@briaguya re: your comment on #2948/#2950/#1891: now that we have the hardcoded privacy policy, I don't see #2950 (content manageable footer links) as a blocker to #2948 (dark nav style). I've updated the dependency. But I'm also going to weigh the priorities on these against other issues.

**Comment by desigonz** [comment]
@briaguya added #2843 to the list, thanks for bringing it up!
