### ISSUE TITLE
Design pin-up

### ISSUE THREAD

**Issue by chasechenevert** [cityofaustin/techstack#3077]
## Agenda
- [x] Simple form style requirements #3008
  - [x] Take a look at the examples, do we have any concerns we need to look into, or guidance to provide?
  - [x] Forms in Guides
- [x] Feedback component into Janis 2 #1840
  - [x] Decide on 1. open field, 2. yes/no buttons and open field
- [x] "Places" and Google maps conversation #2993

## Notes
**Simple form style requirements**
For now we don't have a lot of detailed feedback. We want to see some examples of forms embedded in Guides so that we can determine whether it's better to push those forms to a separate page or keep the forms flow within the Guide.

**Feedback component into Janis 2** 
- We'd rather have some feedback (yes/no) than none at all, so we will go with the yes/no + open text field. We also think the kind of feedback we're looking for might change over time, but our primary use case for Alpha is around Public Health content.
- Update mocks and criteria, then send to dev

**Places**
- We'll narrow the focus to **Department** and **Health** `Places` for now
- Let's develop the data/criteria for those page types
- Specify what `Place`  information gets displayed on different page types (Guides, Information, Service, Department)
- Figure out what's universal across all types
