### ISSUE TITLE
Dev-design sync 10/15

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3080]
- [ ] Navigating to guides from pages and topics
  - [ ] designs TK
- [x] #2581 Joplin main page mock. (*I believe Bob picked up this issue—is there anything you want to review with the design team?*)
  - When you sort a column, the page reloads to our listing page, not the search page. That's problematic from a UX perspective. Dev team, how would you size that fix?
  - Let's review acceptance criteria in general. Is there anything missing?
- [x] Forms
  - tk; does the design team have designs to share? 
- [ ] Managing larger numbers of official document epic (#2668). Per our discussion last week, I split these into multiple issues. Review these issues—dev team, do you need us to clarify anything, or are they read to go?
  - [ ] #3177 removed implied ability to re-order official documents
  - [ ] #3178 collapse official document entires
  - [ ] #3179 official document order display and empty first instance. This would be a good one to review with dev—new acceptance criteria y'all haven't see before.
- [ ] #3149 collapsible contact/location hours—dev team, is there anything in the acceptance criteria you'd like to clarify?
