### ISSUE TITLE
Publish Tech Selection Toolkit Medium post 

### ISSUE THREAD

**Issue by annieszot** [cityofaustin/techstack#3096]
**To-dos before publishing**

[So, you wanna publish a Medium post?](https://docs.google.com/document/d/1KMFASGEiuEkWKdo4jeOmHZOfc02LKVsPiapxvD3IpkU/edit#heading=h.5zkr43xy0rg3)
<br>**Substance**<br>
Show what we did and how we did it:
- [ ] Lessons learned
- [ ] Research
- [ ] Implications
<br>**Content checklist:**<br>
- [ ] Refers to personas
- [ ] Quotes (1+)
- [ ] Photo or graphic (1+)
<br>**Process**<br>
- [ ] Create an issue in Github.
- [ ] Update and complete editorial calendar to set deadlines, ensure accountability and consistent content production. 
- [ ] Compose draft and edit. Aim to write at a grade 8 reading level.
- [ ] Complete A11y best practice checklist.
- [ ] Send to a member of the content team. Update issue and assign with requested deadline to return edits.
- [ ] Revise draft based on edits.
- [ ] Send back to member of the content team for final edits with requested deadline.
- [ ] Prep draft to publish on Medium.
<br>**Images**<br>
- [ ] Choose in-house, project, or public domain photos. Don’t use stock photos. 
- [ ] From in-house, project photos, make sure subjects in photos gave permission (signed a photo release) if they face the camera
- [ ] Favor active versus static subjects in photos.
- [ ] Specify dimensions:
Full column-width images: 1400 px
Out-set images: 2040 px
Screen-width images 2500 px
- [ ] Include one to two sentence caption that’s short, snappy and descriptive. 
<br>**Accessibility: Add Alt-Text to images in Google doc**<br>
- [ ] Select image in google doc
- [ ] Right click (On Mac - Control button + click). Select “Alt Text…”
- [ ] Author alt text
<br>**Add Alt-text to images in Medium.com**<br>
- [ ] Click edit story. Select an image in your story and choose alt text.
<br>**Publish**<br>
- [ ] Create an account on Medium.com.
- [ ] Hover the cursor over your profile photo or initial on (far upper right of screen). 
- [ ] Click, then scroll down to “New story.”
- [ ] Copy and paste your final draft. 
- [ ] Click “Ready to publish?” 
- [ ] **Disable "paywall" content button**<br>
<br>**Congrats! Your writing is out in the world**<br>

**Comment by annieszot** [comment]
[Current draft ](https://docs.google.com/document/d/1m1j9HdYT145moy2Q1wjhRNDq105DZYReQ3E-PFi-2uI/edit#heading=h.jnhf5z258iqx)

**Comment by annieszot** [comment]
Moving milestone to next sprint. Here's Slack convo for next editorial steps
![Screen Shot 2019-10-16 at 5 39 14 PM](https://user-images.githubusercontent.com/46934140/66964739-16efdb00-f03d-11e9-89c1-91a9b5abdd94.png)

**Comment by annieszot** [comment]
Suggested edits back to @ADoAboutThings. Proposing Wednesday, October 23 publish date or earlier.

**Comment by annieszot** [comment]
https://medium.com/civiqueso/a-people-first-approach-to-public-procurement-introducing-a-technology-selection-toolkit-173bb500caf0
