### ISSUE TITLE
Implement feedback component

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3147]
We need to re-introduce the ability for users to submit feedback about alpha. 

### Resources
- [Feedback component](http://janis-staging.herokuapp.com/storybook/?selectedKind=Forms&selectedStory=Feedback%20Form&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel) rendered in Storybook
- XD spec: [desktop](https://xd.adobe.com/spec/a1e17b2e-1b43-40ea-6041-eaf6ba807ea8-d7d0/), [mobile](https://xd.adobe.com/spec/a1e17b2e-1b43-40ea-6041-eaf6ba807ea8-d7d0/screen/959f2dfa-e058-4db7-875b-6b4f6b73c528/Feedback-mobile-default-1), [flow view](https://xd.adobe.com/spec/a1e17b2e-1b43-40ea-6041-eaf6ba807ea8-d7d0/grid/)

## Acceptance criteria

**As a resident**
- [ ] I can **submit text feedback** about a page on Alpha
- [ ] So that **I can inform the Alpha team of my feedback**

**Criteria**
- [x] Just before the global footer, users can see a feedback question [Did you find what you're looking for on this page?] with yes/no buttons set in the secondary styling (fill: `#F0F0F0`, border: `#C6CACE`, `box-shadow: 0px 3px 6px #00000014;`, hover: `#D9E8F6`
- [x]  **User makes yes/no selection**
    - [x] selected button turns dark blue `#2F4668`, remove drop-shadow; non-selected button fill changes to `#F0F0F0`
    - [x] component expands downwards to reveal text, "Tell us more..." text, and an `open text field (not required)`with a primary "submit" button below the open text field. 
    - [x]  User can see character limit countdown [specify character limit]
- [x] **Deselect** a user should have the ability to deselect an option by clicking the selected option to return the component to the original state and button styling
- [x]  **Submit**: when user selects "submit" the button label changes to the "sending" state (as we have it in forms where the 3 dots animate), and their response should turn gray `#ADADAD`
    - [x]  When submitted successfully, button turns green with white checkmark, indicating the feedback was successfully recorded. 
    - [x] success display, "Feedback received. Thank you for helping improve this website!" with a green success badge below
- [ ] **Logging feedback**
  - [ ] resident feedback is recorded and a Github issues is created (based on how the previous feedback component worked [here](https://github.com/cityofaustin/alpha-feedback/issues))
  - [ ] Record device and browser info

**Comment by chiaberry** [comment]
This is on netlify here: https://deploy-preview-568--janis.netlify.com/
It's currently being code reviewed @desigonz , but needs to get checked visually too. One thing I realized was that there is no error handling, if the server goes down and the issue isn't submitted to github, the form just fails quietly. 

The github repo with the issues is here: https://github.com/cityofaustin/alpha-feedback/issues

**Comment by desigonz** [comment]
Assigning @chasechenevert to review the visual design implementation at this [link](https://deploy-preview-568--janis.netlify.com/). Please log your feedback here!

I'm also going to ask the content team an editorial question on Slack and will post the response here.

**Comment by desigonz** [comment]
Here's the copy update:
- [ ] Change `Feedback received.' to `We have received your feedback.`

I'm going to log error messaging specs in a different issue.

**Comment by chasechenevert** [comment]
@chiaberry Could we grab like 30 minutes to look at this together? It's almost there, just a few things that we can look at in the XD document that can help us get to complete.

**Comment by chasechenevert** [comment]
I've created a [new first page for the mockup](https://xd.adobe.com/spec/a1e17b2e-1b43-40ea-6041-eaf6ba807ea8-d7d0/) to isolate the component and I've made the spacing visible (previously you'd have to mouse in over the area to see the spacing). Also on the right hand menu with the </> icon, when you've got that view active you can click into elements to extract the styling.

**Spacing**
- [ ] Spacing, desktop: spacing between elements is 30px
- [ ] Spacing, mobile: spacing between elements is 20px

**Buttons**
- [ ] Font-size: 14px
- [ ] Yes/no, dimensions: h: 48px, w: 130px
- [ ] Submit, dimensions (desktop): h: 48px, w: 180px
- [ ] Submit, dimensions (mobile): h: 48px, w: 278
- [ ] Yes/No buttons, default state, border:  1px solid `#C6CACE`
- [ ] Yes/No, selected: Fill color: #1A4480

**Non-selected button**
- [ ] Fill: #F0F0F0
- [ ] Border-color: #C6CAC
- [ ] Border: 1px

**Rule line**
- [ ] desktop: w: 569px
- [ ] Color #DBDBDB

**Text field**
- [ ] Character limit top border color: #DCDEE0
- [ ] Text field border: #A9AEB1

**Comment by chasechenevert** [comment]
Also just wanted to shout you out @chiaberry for blazing through this! Great work, and glad that you're here!

**Comment by chiaberry** [comment]
thank you @chasechenevert ! I didn't know about the </> icon. I'll incorporate these changes and then we can sync up next week, sound good?

**Comment by desigonz** [comment]
- [ ] change character limit to 2000
- [ ] sending button shifted down
- [ ] submit entry
- [ ] @desigonz to make issue for error handling

@chiaberry to integrate changes then assign @desigonz to QA triage
