### ISSUE TITLE
Dev-design sync 10/22/19

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3203]
## Housekeeping
- Let's develop an acceptance criteria handoff checklist for Janis things that keep slipping through the cracks:
  - Mocks for all breakpoints
    - Desktop
    - Tablet
    - Mobile
  - Translations
  - Previews
  - What else?

## Review implementation
- [x] #3147 review implementation of the feedback module

## Review designs
- [x] #3094 Guide page TOC breaks when too tall. Let's review @chasechenevert's thoughts and see if it's feasible; there was a lot of back and forth with no conclusion.
- [x] Navigating to guides from pages and topics
  - [x] #3033 designs: https://xd.adobe.com/spec/e2cdc032-9eba-4140-5274-fc14f7254296-94fc/
- [x] #2912 Pagination for official docs 

## Other 
- [x] [Tori's timezone question](https://austininnovation.slack.com/archives/C8T4YD23T/p1571684746004000)

## For next week
- [ ] Place content type mocks
  - [ ] #3149 collapsible contact/location hours—dev team, is there anything in the acceptance criteria you'd like to clarify? Design team, let's loop this into the place content type. 
- [ ] Best practice for CSS: rems or pixels?
