### ISSUE TITLE
Pagination style component on official documents

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3247]
## As a resident I want to see a smaller amount of official documents at a time so that I don't have to scroll deep within a page to find an official document.

More context on #2912 .

We've discussed developing this as a storybook component that could be repurposed in the future.

## Code examples for number span with truncation
- https://codepen.io/allicarn/pen/jPowab
- https://codepen.io/Mobius1/pen/gLdzJg

# Criteria
XD Specs: https://xd.adobe.com/spec/aed4d8fc-6ddb-4576-65e2-4125fdb42e8a-d8e5/

**Truncation**
- [x] Desktop and mobile should truncate, so the above example of ["12 Elements"](https://codepen.io/allicarn/pen/jPowab) is the one we're going for
- [ ] Mobile max number of links before truncation: 4 pages are displayed before truncation kicks in. We'll need to fiddle with this when implemented because the spacing is so narrow.
- [ ] Desktop max number before truncation: 7
- [ ] Number of pages on either side of the active page link: 1
- [ ] Truncation behavior: if truncation lands on the left of the center page, clicking on it should act as the "previous" button does by going back one page. If truncation lands on the right side of the center number, clicking on it should act as the "next" button does by advancing one page.

**Previous and Next buttons**
- [x] Default state: tertiary style (gray fill, no border, primary blue text and icon) since these just control moving back and forward and are distinct from the page numbers which represent the pages themselves.
- [x] Hover: fill `#0049C7`, text and icons `#FFFFFF`
- [x] Click: fill `#162E51`, text and icons `#FFFFFF`
- [x] Desktop: should show "Previous" and "Next" text labels to make things clear
- [x] Mobile: should only use left and right chevrons to save space

**Page numbers**
- [x] Page numbers should be horizontally centered between "Previous" and "Next" buttons
- [x] Dimensions, desktop: height 48px / width 48px, number is centered vertically and horizontally within this object
- [ ] Dimensions, mobile: height 48px / width 38px (we may need to fiddle with this once it's implemented because the spacing could be too tight)
- [x] Default style: fill: `#FFFFFF`, text `#212121`
- [x] Active (current page): fill `#D9E8F6`, text `#0049C7`
- [x] Hover: fill `#0049C7`, text: `#212121`
- [x] Select: fill `#162E51`, text `#FFFFFF`

**Copy and translations**
- [x] In English, buttons say `Next` and `Previous`
- [x] In Spanish, buttons say `Siguiente` and `Anterior`

**Unit tests**
- [ ] Unit tests: Will we need to write any unit tests for this content type or feature set?

**Official documents page**
- [x] Pagination component appears at the bottom of the official document page when there are more than 10 of entries
- [ ] Pagination component doesn't appear on an official doc page when there are 10 entries or fewer.

**Comment by desigonz** [comment]
- [ ] when user clicks on a number or next or preview (aka goes to another page via pagination), page scrolls to the top

**Comment by robbobfrh84** [comment]
Ok, this is ready for QA! @desigonz 

PR: https://github.com/cityofaustin/janis/pull/616

Deployed: https://janis-3247-pagination.netlify.com

Or, this URL takes you directly to the official complaint and discipline documents page....
https://janis-3247-pagination.netlify.com/en/health-safety/police-oversight-2/police-feedback-and-records/official-complaint-and-discipline-documents/

- - - - 😀- - - - 
...However, due to the complexity needed for testing, see this tester PR for more pages as well as the pagination added to the top.

NOTE: this branch is just for testing/tinkering/QA-ing, All official QA should be done on the branch above. 

PR: #624
Deployed: https://janis-pagination-top-tester.netlify.com/en/health-safety/police-oversight-2/police-feedback-and-records/official-complaint-and-discipline-documents/

**Comment by desigonz** [comment]
Assigning to @chasechenevert to review tomorrow, so that we can merge this by end of sprint! We'll also be looking at this during dev-design sync tomorrow.

**Comment by desigonz** [comment]
Some things I'm noticing, but will let @chasechenevert verify:
- [ ] What should the behavior be when you're on page 1 and click "previous", or on the last page and click "next"? Currently, the interactions are the same as when you're on a middle page—you can hover to change the button color, etc—but clicking the button doesn't do anything. Do we want the button to change to an inactive state?
- [ ] Hover colors don't match the acceptance criteria (seems to be the same style as for "select")

**Comment by robbobfrh84** [comment]
You are correct about the hover color! There changes should now be updated in test links!
- Hover color now `#0049C7`
- Active page does not hover

**Comment by desigonz** [comment]
Thanks @robbobfrh84! Assigning this one back to me since @chasechenevert is OOO. More thorough QA coming soon.

**Comment by desigonz** [comment]
Hi @robbobfrh84, beautiful work here. Some thoughts below, we can chat this over at dev-design sync too.

### Acceptance criteria not fully met
- [ ] Number of pages on either side of the active page link: 1 *This is true on desktop but currently not happening on mobile. See screenshot below. 
- [ ] Truncation behavior: if truncation lands on the left of the center page, clicking on it should act as the "previous" button does by going back one page. If truncation lands on the right side of the center number, clicking on it should act as the "next" button does by advancing one page. *I think this means that clicking the `...` will navigate the user to the preview or next page, depending on whether it's on the left or the right of the center page.*
- [ ] Per mocks, I expect the pagination component to stretch the width of the page content (so as wide as the official document descriptions, but they are short across various breakpoints. Let's fix them on:
  - [ ] Mobile
  - [ ] Tablet
  - [ ] Desktop

### Acceptance criteria that we still need to verify
- [ ] Mobile max number of links before truncation: 4 pages are displayed before truncation kicks in. We'll need to fiddle with this when implemented because the spacing is so narrow. *@robbobfrh84 , you've probably implemented this but I can't verify. Can you share the Joplin branch for your app so that I can test this? Or otherwise share links to Janis pages that will allow me to verify?*
- [ ] Desktop max number before truncation: 7 *@robbobfrh84 , you've probably implemented this but I can't verify. Can you share the Joplin branch for your app so that I can test this? Or otherwise share links to Janis pages that will allow me to verify?*
- [ ]  Pagination component doesn't appear on an official doc page when there are 10 entries or fewer. *Again, will need a way to verify this—we'll need to build a page with just a few documents*

![image](https://user-images.githubusercontent.com/5839508/69667615-f7909880-1053-11ea-8df6-4bf9939ec444.png)
![image](https://user-images.githubusercontent.com/5839508/69668086-d3818700-1054-11ea-863b-64e5146e36d1.png)
![image](https://user-images.githubusercontent.com/5839508/69668121-e3996680-1054-11ea-865c-787ee6e05e91.png)

**Comment by desigonz** [comment]
When @chasechenevert is back, let's review these questions
- Mobile max number of links before truncation: 4 (@robbobfrh84 recommends 5, but we'd need to adjust design on smallest screens)
- Per mocks, I expect the pagination component to stretch the width of the page content (so as wide as the official document descriptions, but they are short across various breakpoints. Let's fix them on

**Comment by robbobfrh84** [comment]
Ok, So I'll Update ...
- The "..." ellipsis to the left of the *active page* to act as the _previous_ page as well as the one on the right to be the _next_ page.
- I'll prioritize the previous page# and next page# over ellipsis
  - 👍[<-][1][8][*9*][10][15][->]
  - 👎[<-][1][...][*9*][...][15][->]


Questions Going forward for new issue
- How should we handle width of pagination "Stretching the width of the document" when their aren't enough pages to match that width? (Currently, It's left aligned) .

**Comment by desigonz** [comment]
@robbobfrh84 looks great! I made #3502 to account for the followup issues, but this is ready to go to production.
