### ISSUE TITLE
Formstack theme updates

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3288]
# Checklist for styling
Biggest changes here are:
- **Placement of the hint/help text** Formstack's default places help text below the field it relates to (example of address fieldset). We want this text to appear above the field it relates to.
- **Stroke color around fields**: we've been using a light gray with a thin 1px width stroke, but we need to increase the contrast of these fields for accessibility.

## Acceptance criteria
**Components**
- [x] Heading
  - [x] Font-size: 32px;
  - [x] Color: `#212121`;
  - [x] Margin-top: 6.4rem;
- [x] Label
  - [x] Font-size: 18px;
  - [x] Font-weight: 700; 
  - [x] Color: `#212121`;
  - [x] Margin-bottom: 8px;
  - [x] "Required" label: sits next to the field label, on the same baseline
    - [x] Label text: "(Required)", remove the asterisk, it's a hold-over from USWDS
    - [x] Color: `#D63E04`;
    - [x] Font-size: 18px;
    - [x] Font-weight: 700; 
- [x] Hint text
  - [x] placed below label (not below field as Formstack's default)
  - [x] Font-size: 16px; 
  - [x] Color: `#3D4551`;
  - [x] Margin-bottom: 8px;
- [ ] Error text per fieldset: insert error text below Label text and Hint text
  - [ ] Font-size: 16px; 
  - [ ] Font-weight: 900; 
  - [ ] Color: `#D63E04`;
  - [ ] Margin-bottom: 8px;
  - [ ] (Pushed to https://github.com/cityofaustin/techstack/issues/3392)
- [x] Error: field
  - [x] Border-color: `#D63E04`; 
- [x] Field
  - [x] Height: 48px;
  - [x] Padding: 12px 10px;
  - [x] Border-width: 2px `#000000`;
- [x] Text area: open response
  - [x] Padding: 12px 10px;
  - [x] Border-width: 2px `#000000`;
- [x] Fieldset
  - [x] Margin-bottom: 30px;
  - [ ] (Note- I styled the explicit <fieldset> element. It may be that you also wanted logical sections (Employer Information, Job Information) to have a 30px margin between them.)
- [x] Dropdown
  - [x] Border-width: 2px `#000000`;
  - [x] Border-radius: 2px;
- [x] Checkbox
  - [x] Default: circle stroke color: #000000;
  - [x] Selected color: `#0050D8`;
- [x] Radio button
  - [x] Default: circle stroke color: #000000;
  - [x] Selected color: `#0050D8`;

**Button: default**
- [x] Height: 48px;
- [x] Border-radius: 4px
- [x] Color: `#0050D8`;
- [x] Font-color: `#FFFFFF`;
- [x] Hover: `#2672DE`;
- [ ] Select: `#1A4480`;
  - [ ] (Question- is "Select" after you click on it?)
- [ ] Success: `#00A91C`;
  - [ ] (Note- I don't think Formstack forms have a "Success" state, skipping for now)

**Button: secondary**
- [x] Height: 48px;
- [x] Border-radius: 4px;
- [x] Border-width: 2px;
- [x] Background-color: `#FFFFFF`;
- [x] Border-color: `#0050D8`;
- [x] Text-color: `#0050D8`;
- [x] Hover: `#EFF6FB`;
- [ ] Select: `#1A4480`;
- [x] Text-color: `#FFFFFF`;

Assign @chasechenevert to QA.

**Comment by Niicck** [comment]
Also fix the padding on embedded iframe per the request here: https://github.com/cityofaustin/techstack/issues/3202

**Comment by Niicck** [comment]
Ready for Review:

1. Test out a single page form here: https://janis-3288-content-padding.netlify.com/en/health-safety/health-records-certificates-2/birth-death-certificates/single-page-form-test
2. Test out a multi-page form here: https://janis-3288-content-padding.netlify.com/en/health-safety/health-records-certificates-2/birth-death-certificates/multi-page-form-test

**Comment by desigonz** [comment]
@Niicck awesome work! I did a quick pass and it looks great, a few questions below for Chase to verify. Re: error text per fieldset, as we've discussed separately, we'll make a new issue for that and write to Formstack about it.

@chasechenevert, for the submit button, can you verify text size and padding

For heading, `Margin-bottom: 64px;`—has this been implemented?

The left border here is missing:
![image](https://user-images.githubusercontent.com/5839508/68690225-46f4a600-0537-11ea-8986-aaf4d9730b83.png)

What should the size be for the text circled below?
![image](https://user-images.githubusercontent.com/5839508/68690429-a05cd500-0537-11ea-9856-72b9648683ed.png)
![image](https://user-images.githubusercontent.com/5839508/68690547-cf734680-0537-11ea-9f7c-ad698bb71bee.png)

**Comment by Niicck** [comment]
3rd thing: Spanish forms needed some work making the Zip code field look less awkward (now that its moved above the field). So I made every field label on the same line as Zip Code have the same spacing.
<img width="743" alt="Screen Shot 2019-11-12 at 11 20 03 AM" src="https://user-images.githubusercontent.com/14187277/68694254-74911d80-053e-11ea-8379-1ac015e2ab19.png">
https://janis-3288-content-padding.netlify.com/en/preview/form/UGFnZVJldmlzaW9uTm9kZToyMTM5?CMS_API=https://joplin-pr-nick-testing-machine.herokuapp.com/api/graphql

**Comment by Niicck** [comment]
The problem with changing the size of field labels within the Address Field is that "Zip Code" will extend onto 2 lines. And on Spanish forms it would expand into like 4 lines.

**Comment by desigonz** [comment]
@Niicck good to know!!

**Comment by chasechenevert** [comment]
Testing pasting dev inspect code changes via Firefox. @Niicck let me know if this works for you!

## Changes not reflected in code samples below
- [ ] Focus/Active state: 3px, solid, `#face00`; this should be on the outside of the field
- [ ] Swap Formstack's default icon with [material `calendar_today` icon ](https://material.io/resources/icons/?search=cal&icon=calendar_today&style=baseline) color: `#0050D8`
- [ ] Swap Formstack's back and forward buttons with ours (switches to theirs on mobile view). Let's have those buttons be a bit wider so they're easier to tap: `width 145px`

## Single page
https://janis-3288-content-padding.netlify.com/en/preview/form/UGFnZVJldmlzaW9uTm9kZToyMTM5?CMS_API=https://joplin-pr-nick-testing-machine.herokuapp.com/api/graphql

```
/* default-v4_f1d5918f48.css | https://static.formstack.com/forms/css/3/default-v4_f1d5918f48.css */

.fsValidationError .fsLabel, .fsValidationError .fsRequiredLabel, .fsValidationError .fsRequiredMarker {
  /* color: #ce5f6d !important; */
  color: #D63E04 !important;
}

div.fsError {
  /* color: #ce5f6d; */
  color: #D63E04;
}

div.fsError {
  /* text-align: center; */
  text-align: left;
}

.fsValidationError .fsMatrix, .fsValidationError .fsOptionLabel, .fsValidationError .fsSupporting {
  /* color: #797d88 !important; */
  color: 3D4551 !important;
}

/* Inline #-1 | https://janis-3288-content-padding.netlify.com/en/preview/form/UGFnZVJldmlzaW9uTm9kZToyMTM5?CMS_API=https://joplin-pr-nick-testing-machine.herokuapp.com/api/graphql */

.fsFieldCell > .fsSupporting, .fieldset-content > .fsSupporting {
  /* line-height: 1.6rem; */
  /* margin-bottom: .8rem; */
  line-height: 2rem;
  margin-bottom: 1rem;
}

.fsForm select, .fsForm select.fsRequired {
  /* padding-bottom: 12px; */
  padding-bottom: 1.2rem;
}

.fsBody .fsForm .fsSectionHeading {
  /* line-height: 1em; */
  line-height: 4rem;
}

/* Inline #-1 | https://janis-3288-content-padding.netlify.com/en/preview/form/UGFnZVJldmlzaW9uTm9kZToyMTM5?CMS_API=https://joplin-pr-nick-testing-machine.herokuapp.com/api/graphql */

label.fsOptionLabel {
  /* font-size: 14px; */
  /* line-height: 28px; */
  font-size: 1.6rem;
  line-height: 2rem;
}

.fsBody .fsSupporting {
  /* font-size: 12px; */
  /* line-height: 12px; */
  font-size: 1.6rem;
  line-height: 2rem;
}

.fsBody .fsForm .fsSectionHeading {
  /* margin-bottom: 10px; */
  margin-bottom: 2rem;
}

div.fsError {
  /* font-size: 14px; */
  font-size: 1.6rem;
  line-height: 2rem;
}

.fsFieldFocused div.fsSupporting {
  /* color: #595d64; */
  color: #3d4551;
}

.fsBody .fsLabel, .fsBody label {
  /* color: #595d64; */
  color: #212121;
}

@media (max-width: 40em) {
  label.fsOptionLabel {
    /* border: 1px solid #cfd4d8; */
    /* border-radius: 0px; */
    /* background-color: #edeff0; */
    /* color: #595d64; */
    border: 2px solid #000;
    border-radius: 4px;
    background-color: #f1f3f6;
    color: #212121;
  }
}

```

## Multipage
https://janis-3288-content-padding.netlify.com/en/health-safety/health-records-certificates-2/birth-death-certificates/multi-page-form-test/

```
/* Inline #-1 | https://janis-3288-content-padding.netlify.com/en/health-safety/health-records-certificates-2/birth-death-certificates/multi-page-form-test/ */

@media (max-width: 40em) {
  label.fsOptionLabel {
    /* border: 1px solid #cfd4d8; */
    /* border-radius: 0px; */
    /* background-color: #edeff0; */
    /* color: #595d64; */
    border: 2px solid #000;
    border-radius: 4px;
    background-color: #f1f3f6;
    color: dcdee0;
  }
}

.fsBody .fsRowBody {
  /* margin-bottom: 20px !important; */
  margin-bottom: 3rem !important;
}

.fsBody .fsLabel, .fsBody label {
  /* color: #595d64; */
  color: #212121;
}

/* Inline #-1 | https://janis-3288-content-padding.netlify.com/en/health-safety/health-records-certificates-2/birth-death-certificates/multi-page-form-test/ */

.fsFieldCell > .fsSupporting, .fieldset-content > .fsSupporting {
  /* line-height: 1.6rem; */
  line-height: 2rem;
}
```

**Comment by Niicck** [comment]
Comments:
`.fsBody .fsForm .fsSectionHeading {line-height: 4em;}`
+ `.fsBody .fsSectionHeader {margin-bottom: 6.4rem;}`
creates a giant gap between sections. Wondering if using both is intentional.

**Comment by Niicck** [comment]
- I don't think `.fsBody .fsForm .fsSectionHeading {line-height: 4em;}` is actually what you want. Because when a Section Heading goes into multiple lines it really doesn't look good:  https://janis-3288-content-padding.netlify.com/en/health-safety/health-records-certificates-2/birth-death-certificates/multi-page-form-test/

**Comment by Niicck** [comment]
- On the multipage styling section:
```
@media (max-width: 40em) {
  label.fsOptionLabel {
    /* border: 1px solid #cfd4d8; */
    /* border-radius: 0px; */
    /* background-color: #edeff0; */
    /* color: #595d64; */
    border: 2px solid #000;
    border-radius: 4px;
    background-color: #f1f3f6;
    color: dcdee0;
  }
}
```
Why is only the color different here?

**Comment by Niicck** [comment]
- Is this a change you want to see only on "multi-page forms"?
```
.fsBody .fsRowBody {
  /* margin-bottom: 20px !important; */
  margin-bottom: 3rem !important;
}
```

**Comment by chasechenevert** [comment]
> * I don't think `.fsBody .fsForm .fsSectionHeading {line-height: 4em;}` is actually what you want. Because when a Section Heading goes into multiple lines it really doesn't look good:  https://janis-3288-content-padding.netlify.com/en/health-safety/health-records-certificates-2/birth-death-certificates/multi-page-form-test/ Would you prefer to have some `margin-top` to go with the specified `margin-bottom: 64px`?

- [ ] Changing `4em` to `4rem` seems to fix the first part
- [ ] the margin-bottom from the original criteria list is an error on my part. It should be `margin-top: 6.4rem` and I've updated it in the criteria up top

**Comment by chasechenevert** [comment]
> Comments:
> 
> * `.fsBody .fsForm .fsSectionHeading {line-height: 4em;}` + `.fsBody .fsSectionHeader {margin-bottom: 6.4rem;}`
>   creates a giant gap between sections. Wondering if using both is intentional.
>   It also renders null the `.fsSectionHeading { /* margin-bottom: 10px; */ margin-bottom: 2rem; }` requirement

- [ ] changing 4em to 4rem seems to fix it
- [ ] `margin-bottom: 6.4rem`  should be `margin-top: 6.4rem`, which should clear up the conflicting bottom margins

**Comment by chasechenevert** [comment]
> * On the multipage styling section:
> 
> ```
> @media (max-width: 40em) {
>   label.fsOptionLabel {
>     /* border: 1px solid #cfd4d8; */
>     /* border-radius: 0px; */
>     /* background-color: #edeff0; */
>     /* color: #595d64; */
>     border: 2px solid #000;
>     border-radius: 4px;
>     background-color: #f1f3f6;
>     color: dcdee0;
>   }
> }
> ```
> 
> Why is only the color different here?

Not sure where the `color: dcdee0;` is coming from, but it's an error on my part. everything else here looks good.

**Comment by chasechenevert** [comment]
> * Is this a change you want to see only on "multi-page forms"?
> 
> ```
> .fsBody .fsRowBody {
>   /* margin-bottom: 20px !important; */
>   margin-bottom: 3rem !important;
> }
> ```

Nah, let's have this be the same everywhere. It was only visible to me in the mobile view of the multipage form, probably because that one has checkboxes and the other doesn't.

**Comment by chasechenevert** [comment]
- [ ] Button micro-copy: "back" and "continue"

**Comment by Niicck** [comment]
Alright. All style change requests have been implemented. We should be very close to done, but maybe there are some final changes to be made.

- Single Page: https://janis-3288-content-padding.netlify.com/en/health-safety/health-records-certificates-2/birth-death-certificates/single-page-form-test
- Multi Page: https://janis-3288-content-padding.netlify.com/en/health-safety/health-records-certificates-2/birth-death-certificates/multi-page-form-test
- Spanish Page: https://janis-3288-content-padding.netlify.com/en/preview/form/UGFnZVJldmlzaW9uTm9kZToyMTM5?CMS_API=https://joplin-pr-nick-testing-machine.herokuapp.com/api/graphql

**Comment by chasechenevert** [comment]
Nick--it looks great! The final thing that I see is for multi-page form, final screen where we have "Back" and "Submit Form" buttons, let's get those on the same line and then we're all set!

**Comment by Niicck** [comment]
Done.
