### ISSUE TITLE
Font implementation: Heading and paragraph margin adjustments

### ISSUE THREAD

**Issue by chasechenevert** [cityofaustin/techstack#3337]
Still adding to this!

## H2
Adjusts headings so that the spacing is 2x larger than paragraph spacing. 
- Service
- Information
- Guide

From
```
margin-top: 0;
margin-bottom: 3rem;
```
to
```
margin-top: 4rem;
margin-bottom: 2rem;
```

## H3
From
``` margin-bottom: 
```

To 

## Paragraph
Slightly more spacing between Headings and paragraphs, now proportional. 

From
```
margin-top: 1.7rem;
margin-bottom: 1.7rem;
```

to
```
margin-top: 2rem;
margin-bottom: 2rem;
```

# Department page: heading, paragraphs
Headings on these pages is using a different class that’s not consistent with other parts of alpha. 

### Headings, H2 class=”coa-SectionHeader”
From
```
padding-top: 3rem;
font-size: 2.4rem;
font-weight: 700;
margin-bottom: 2rem;
```
to
```
padding-top: 4rem;
font-size: 3.2rem;
font-weight: 500;
margin-bottom: 2rem;
```
## Paragraphs
- [ ] Type block in “about director” doesn't have paragraph tags and it’s causing the spacing to look off. Should have the <p> values above.
- [ ] Paragraph and list are nested within another `<p>`, which seems to be causing the group to inherit additional margin and padding. Haven't looked in Joplin to see if this is because these are forced line breaks.
- [ ] List styling needs to match service page (recently implemented by Chia)

**Comment by chasechenevert** [comment]
Don't have anything else to add to this at the moment. Not sure how a dev would want this broken out, but we probably will need to QA each of these changes to make sure nothing weird happens.
