### ISSUE TITLE
Design pin-up #1, Sprint 43

### ISSUE THREAD

**Issue by chasechenevert** [cityofaustin/techstack#3347]
# 🏆 **Objective** 
Review our current thinking on these issues, get feedback, create next steps.

# ✋ **Participants**

Anyone can attend, but this pin-up will need content feedback the most.

# 📓  **Agenda**
- [x] 🐾 Joplin content manageable footer: https://github.com/cityofaustin/techstack/issues/2950, and https://github.com/cityofaustin/techstack/issues/3211
- [x] 🌐 Janis translation messaging UI: https://github.com/cityofaustin/techstack/issues/3341
- [x] 🔗 Janis department mega link list: https://github.com/cityofaustin/techstack/issues/3263

------
- [x] Schedule meeting
- [x] Meet
- [x] Add notes to doc: [Design pin-up / Sprint 43](https://docs.google.com/document/d/1_OdrjHgNbflvQt65KOQrliobt3baaZxgfc8efF8RMic/edit?usp=sharing
)
