### ISSUE TITLE
Dev-design sync 11/12/19

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3362]
- [x] #3371 video embeds
- [x] Recollect things
  - [x] #3399 
  - [x] #3122 
- [x] #3263 department page mega list
- [x] #3379 requirements for custom save/publish logic (#3268 for additional context)
- [ ] Location content type mega-issue #3400 (we'll break this down)
- [ ] #3211 footer editing
- [ ] are we ready for meta-view of topics? re: joplin 3.0

**Comment by easherma** [comment]
Tori and I also talked about setting https://django-recurrence.readthedocs.io/en/latest/usage/getting_started.html up on a branch of joplin so she could play around with setting exclusions/setting up recurring events.
