### ISSUE TITLE
Implement location content type

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3400]
## Note
Thinking of splitting this into multiple issues:
1. Joplin implementation for content type
2. Janis implementation for content type
3. Location/contact display on service and department pages 
4. Hours

## Janis: location page (sprint 44)
- [ ] Implementation matches mocks
  - [ ] [desktop](https://xd.adobe.com/spec/d7653e44-403a-4620-4436-1484993d4622-a154/screen/62dce76d-7739-43a1-a958-9c2e122b74f8/Template-Places-MVP-Desktop)
  - [ ] [Tablet](https://xd.adobe.com/spec/d7653e44-403a-4620-4436-1484993d4622-a154/screen/64aa180d-e5d8-470f-a53b-9fc814a37d57/Template-Places-MVP-Tablet)
  - [ ] [Mobile](https://xd.adobe.com/spec/d7653e44-403a-4620-4436-1484993d4622-a154/screen/8b743758-76df-4678-8e92-0d8e7b66c31d/Template-Places-MVP-Mobile)
- [ ] Page preview implemented
- [ ] Translations: when page viewed in Spanish, the following microcopy is translated

| English copy        | Spanish copy           | 
| ------------- |-------------|
| *Contact*     | Contacto  |
| Phone     |  Teléfono     |
| Email address | Correo electrónico      |
| *Location*     | Ubicación  |
| Physical address     |  Dirección física     |
| Mailing address |  Dirección postal     |
| *Facility hours*     |  Horario del centro     |
| Standard hours |   Horario regular    |
| *Services offered*     |   Servicios ofrecidos    |
| Service information |  Información sobre el servicio     |
| See more hours     |  Vea otros horarios     |
| Close hours |   Cierre horarios    |
| *Getting here*     |  Cómo llegar     |
| Buses servicing this area   |   Autobuses del área   |

## Joplin: location page (sprint 44)
Mock: ![Locations](https://user-images.githubusercontent.com/3790067/68501944-fc1c1b00-0224-11ea-9bbc-f18b3eac8a95.png)

## Service/department page (sprint 44 or 45?)
Let's review what it looks like to navigate to the location page from a service or department.
[Desktop](https://xd.adobe.com/spec/d7653e44-403a-4620-4436-1484993d4622-a154/screen/2a5af05a-3afb-4293-a312-96d5d333e375/Template-Service-list-desktop)
[Mobile](https://xd.adobe.com/spec/d7653e44-403a-4620-4436-1484993d4622-a154/screen/431f2b3c-5299-483c-adda-ed32d1951136/Template-Service-list-desktop)

**We probably need mocks for what this looks like from the Joplin side of things**

### MVP
- [ ] Authors can select discontinuous hours within the same day. 
  - Ex. 9am – 12pm, 1pm – 5pm
  - [ ] On Janis, discontinuous hours display matches [mocks](https://xd.adobe.com/spec/d7653e44-403a-4620-4436-1484993d4622-a154/screen/62dce76d-7739-43a1-a958-9c2e122b74f8/Template-Places-MVP-Desktop/) 
- [ ] Text field to add any kind of irregularity

### Post-MVP
- [ ] Hours display the same on Janis staging, Janis prod, and previews 
- [ ] Authors are able to select time using 12 hour clock in Central Time zone
  - [ ] Quarter hour and half hour increments
- [ ] Authors can indicate monthly/bimonthly extra opening hours AND closures
  - Ex. 1st and 3rd Saturday of the month: 8am – 12pm
  - Ex. Closed 2nd Wednesday of each month
  - [ ] **Design:** Need mocks for how this displays on the Janis side of things
- [ ] Authors can indicate that a service/department/location is closed on all City of Austin holidays
  - [ ] **Design:** Need mocks for how this displays on the Janis side of things. (For MVP, could display with hours: "Closed on all [City of Austin holidays](/x)" with a link to an info page with closures. When we get to designing calendar of events, could also sync with that)
  - [ ] **Design:** What would this look like on the author side of things? A simple checkbox "closed on City holidays" could be nice!
    - Then we have the added question of where we manage City holidays.
- [ ] **Maybe**: Ability to add string text for special holiday hours or closures that don't have a pattern. We could potentially use this for unplanned closings due to emergencies or other one-offs.
  - Ex. Closing at 2pm on New Years Eve (for a place that might close at 5 regularly) 
  - [ ] **Design and content:** Need requirements for how this displays on the Janis and Joplin side of things. What does this look like to a resident? What guidance do we provide on the author interface?

### Collapsible hours
#3149
- [ ] *need to specify interaction behaviors*

**Comment by Niicck** [comment]
Hours:
  - use existing hours UI, with a text field for edge cases

**Comment by easherma** [comment]
Also, will spin up https://github.com/django-recurrence/django-recurrence in Joplin for Tori to play with

**Comment by desigonz** [comment]
MVP for URLs: `/locations/slug`

**Comment by toribr** [comment]
Updated location based which includes additional text field for outlying hours which cannot be represented by basic controls.
https://xd.adobe.com/spec/d3fea86b-184d-4652-48b2-48ce78dcb3ae-a5cf/

**Comment by toribr** [comment]
A requirement that may not be captured elsewhere:
Many of the services start or stop on the quarter hour. That means that we'll need to allow for 7:00, 7:15, 7:30, 7:45, etc. Will make the drop down longer but there's no way around it. Also, we need to make the times on the 12:00 (US) clock, which means we'll have to add a separate control for AM/PM.

**Comment by desigonz** [comment]
You can currently add more specific times (quarter hour and half hour) using the current widget by typing in the number. The UX for authors isn't ideal because the dropdown seems to indicate you can only choose times on the hour, but it works for MVP. Let's include this when we make a new issue for rehauling the hours widget.

![image](https://user-images.githubusercontent.com/5839508/69454296-7c657480-0d2b-11ea-8b49-f62c05379cb4.png)

**Comment by toribr** [comment]
I disagree that this is acceptable for MVP. Just because it "works" isn't a measure by which a feature should be marked good enough. The widget shouldn't imply one thing and do another. That's lazy. It should at least show the times in quarter hours, even if no validation takes place.
