### ISSUE TITLE
Alternative Payment Options SDL Engagement

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3438]
- [x] @ADoAboutThings and @Jo-Dwyer to talk with Amy Schillerstrom about how to interview stakeholders
    - [x] judges
    - [ ] clerks
    - [ ] defendants
    - [x] community service administrator
    - [ ] community service providers
- [x] @ADoAboutThings to scope and sketch an preliminary timeline
    At what point do we start the process (citation? guilty plea?) and where does it fit into a bigger chain of options.
- [x] @desigonz This has a lot of stakeholders, a lot of requirements and a long-term time commitment. Make this an Epic?

**Comment by desigonz** [comment]
Epic made!

**Comment by Jo-Dwyer** [comment]
@Jo-Dwyer to:
- [ ] get a soft copy of Municipal court's internal process maps from Amy
- [ ] list of names direct stakeholders
    - [ ] who is answering the phone when I call for financial affidavit
- [ ] what are the ethics surrounding interviewing applicants/defendants
- [ ] results from Municipal court survey

**Comment by ADoAboutThings** [comment]
### [Research Plan] that was shown to Amy S. (https://docs.google.com/presentation/d/17PRLwblwaYpWbD-TsX-F04JrvfNsVzilQAl--pu6XHA/edit#slide=id.g7911f2d61e_1_54)


**Notes**
-Financial affidavits can be called in. They can set you up on a standard payment plan. 
-Judges still need to be involved to make decisions around whether to grant an alternative payment. 
-E-signatures from defendants are acceptable. Unclear if e-signatures to notarize is. 
-Judges can receive information online and have documents forwarded to them. 

Action Items
- [ ] Follow-up with Amy on survey results

- [ ] Follow-up with Amy on soft copy of process workflow. 

- [ ] Follow-up with Amy on stakeholders to speak to.

**Comment by Jo-Dwyer** [comment]
@ado are you satisfied with the survey results that Amy shared?

**Comment by Jo-Dwyer** [comment]
We're connecting with Kim Wingard about the form workshop for community service. Pertinent questions are in #3270, but answers will come out of workshop.
