### ISSUE TITLE
Design Pin-up (Sprint 45) Dec 3, 2019

### ISSUE THREAD

**Issue by toribr** [cityofaustin/techstack#3511]
## Agenda
- [x] (#3421) Review parity of handicap accessibility: Joplin v Janis
- [x] (#2741) Pending translations
- [x] (#3497) Page transition
- [x] (#3399) Recollect Janis skin
  - [ ] **Dev**: There are a few things that have been removed (navigational elements), and lots of restyling so most of the questions are around what’s achievable and how much effort is required. Also pretty concerned about Recollect pushing any updates and the potential of breaking the app.
  - [x] **Content**: could use your help looking through the microcopy since I’ve made some changes on the fly. I’m not sure if Content’s review is a requirement, but it’s worth considering what recommendations y’all might have when displaying third-party applications on Alpha
  - [x] **UX and UI**: there are a few patterns that I’ve replicated but I think we should reconsider.

**Comment by chasechenevert** [comment]
## To-dos
**Location page**
- [ ] Accessibility information: create issue for the next phase of accessibility research and criteria for the location page, and create doc for cross-team collaboration
- [ ] "Accessibility" header label: this question is coming up again for us. Currently the section on the Location page is "Getting here" but we suspect that residents are scanning for this keyword to help them find this information.
- [ ] Wheelchair access: we're going to wait for feedback from David before finalizing anything
  - [ ] Joplin: which pattern to land on? Radio yes/no buttons?
  - [ ] Janis: create new H2 for this section. Will need content to approve the label

**Pagination**
The page load is so instant that it almost doesn't look like the page has reloaded anything. We need to introduce some animation as a subtle cue that new information is now visible in the viewport. 
- [ ] Let's see if we can get dev to create a branch to see this animation: https://codepen.io/novecentonove/pen/abbdjVj

**Comment by toribr** [comment]
(#3421) This issue is going to get more research regarding using a yes/no input and how to frame "not accessible."
