### ISSUE TITLE
Prioritize Joplin 3.0 UX improvements

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3523]
Author interface feature and improvements that will require significant code refactor to implement.

**Comment by desigonz** [comment]
### By June 
- [ ] Joplin UI: type and color #4082
- [ ] Revision history for snippets #3527 
- [ ] Bidirectional relationships (or should this be based on specific user stories?)

### By end of 2020
- [ ] Rethink how we handle translations #2926
- [ ] Topic and topic collection (IA) management #2223 

### Much lower priority than the above
- [ ] Batch publish/unpublish #2268
- [ ] "Archive" pages #694
- [ ] Improve top-level page UX #3619 
- [ ] Revision history—don't save/show duplicate drafts #2286
- [ ] Joplin page listing filters #2349
- [ ] Author-friendly UI for adding things within rich text blocks (tables, buttons, adding apps)

**Comment by ablangworthy27** [comment]
This looks pretty good to me. I think we are hoping that a very strong strategy is in place for translations well before December 2020. But June wouldn't be possible, so I guess it is placed exactly where it belongs!

One other thing is the Author-friendly UI for rich text blocks. I think depending on when we start onboarding real users, this may become necessary sooner than we realize.

**Comment by desigonz** [comment]
Thanks for your feedback, @ablangworthy27! 

Re: translations comments: the work I'm referring to here would be a major overhaul of the design or development around translations; if there are smaller fixes we could implement to support translations that _don't_ require a big technical refactor, we could do those sooner.

And for author-friendly UI stuff—noted. We might want to push this up to June if it's doable.

**Comment by toribr** [comment]
There's a lot of issues missing.

There's no mention of home page efforts. Is that intentional?

Depending on the timing of rolling out Joplin to more users, there's some problematic flow issues, like the inability to add an image to a page without actually needing to leave the page, which should be solved with modals. There are other similar basic patterns which result in poor usability which should be addressed, like the lack of either/or within components, ie radio button. There's also some weird "requirements" signaling, because the component container isn't marked but the component within is. See "Contact" for reference. In my view, there are quite a few more basic Joplin UI fixes that should be done this year that if not addressed are going to be significant impediments to non-Flock authors' successful use of this tool.

**Comment by desigonz** [comment]
This is not all things, and it's not even all Joplin things—it refers to things that will require significant refactor in order to accomplish it. 

Send me issues for all of the things you mentioned above, and I can work with dev to determine whether they are Joplin Alpha (no need to refactor) or Joplin 3.0 (refactor needed), and then we'll fit them on the roadmap. Make sure to include user stories on the issues, that will be helpful too!

**Comment by desigonz** [comment]
☝️ Each of the issues above is now an epic. Here's how the issues are organized in the backlog:

| Roadmap        | Where it is in the backlog           |
| ------------- |:-------------:|
| P1: By June      | Next sprint candidates/on deck/in progress |
| P2: End of 2020      | Short-term backlog      |
| P3: Next priority | Medium/long-term backlog    |
| P4: Low priority | Icebox |

Again, note that this is refactor-dependent features, not all issues.

If there are more things I should consider in the roadmap/priority, please send the issues/user stories my way. For now, closing this issue!
