### ISSUE TITLE
Dev-design sync 12/10/19

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#3538]
## Designs/requirements to review
Pagination
- [x] #3502 pagination review—goal is to create issues for next sprint
- [x] #3497 pagination transition

Various things
- [x] #3537 Inserting documents into rich text fields
- [x] #3378 departmental permissions
- [x] #3416 Joplin UI style improvements

If time permits?
- [x] #3500 pending translation
