### ISSUE TITLE
Research roadmap meeting

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#3767]
Let’s meet to align our priorities for research with the roadmap.

- [ ] Define what we want to get out of potential research
- [ ] Understand capacity and scope
- [ ] Look at the roadmap and see where we have opportunities to do research
- [ ] create resulting issues
