### ISSUE TITLE
Dev design sync - 2/18/2020

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#3962]
- [ ] https://github.com/cityofaustin/techstack/issues/3874#issuecomment-586517508 event fees/free
- [x] Review Wagtail 2.8 changes https://github.com/cityofaustin/techstack/issues/3912#issuecomment-586468578
- [x] https://github.com/cityofaustin/techstack/issues/3925 privacy blocker tracking
- [x] #3926 Error states for save/publish requirements https://share.goabstract.com/2217505d-e313-49b5-a420-2e889036bf8f?
- [x] discuss https://www.abstract.com/ @chasechenevert mentioned it in his standup on 2/11, is it something we're trying to implement into our flow? You can join as a viewer here: https://app.abstract.com/invitations/7dbdc4aa499a6e41e0e9856af39507f41e004e585e11368a591e48a40a162027

**Comment by chasechenevert** [comment]
You can join as a viewer in our Abstract space here: https://app.abstract.com/invitations/7dbdc4aa499a6e41e0e9856af39507f41e004e585e11368a591e48a40a162027
