### ISSUE TITLE
Wagtail Data Model Updates

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/techstack#418]
- [ ] Create a BasePage Model (related to #634)
  - mainly for testing
  - also with our array of statuses:
    - `drafted`, `in review`, `archived`, `published`, `unpublished`

- [ ] Update Service Page Model #427 #663 
  - needs more than one topic
  - _should it be an array? or primary & secondary?_
  - update Step attr to be an expandable array of Rich Text fields up to 10

- [x] Create Process Page Model #396 
- [ ] Department Page Model #664

- [ ] User Permission Model & User Settings #537 #539 #666
  - super user -> dept admins (has a dept, has admin rights based on themes/topics they can add ppl to) -> content editors can draft, edit, archive content within their topics
  - _where do publishers/reviews fit into this? 

- [ ] Contacts #665
  - service page and process page should only have 1 contact

- [ ] RichTextField #476 
  - review if richtext fields can be made into translatable streamfields (modeltranslation library needs to be updated for this)

**Comment by amenity** [comment]
@briaguya - I think you captured all of this in other issues, thanks! 

I'm putting these on deck for Sprint 14 so they need to be sized ASAP: 
#663 - Update Service Page model
#634 - Create CoA base page model
#665 - Update service/process pages to only have 1 contact 

The others are just chillin' in the backlog for now. ❄️
