### ISSUE TITLE
End-to-end Regression Tests for Alpha

### ISSUE THREAD

**Issue by Niicck** [cityofaustin/techstack#4213]
An in-progress list of things we want to check in an end-to-end Alpha test.

Issues found so far:
| Link | Title | What are we doing about it? |
| - | - | - |
| https://github.com/cityofaustin/techstack/issues/4333 | Changing languages when previewing a page | dealing with it later |
| https://github.com/cityofaustin/techstack/issues/4332 | Spanish content 404s  | actually just https://github.com/cityofaustin/techstack/issues/4347 |
| https://github.com/cityofaustin/techstack/issues/4334 | Unpublished pages staying published | [switched to always rebuild for now](https://github.com/cityofaustin/joplin/pull/709), we'll investigate after we're in prod |
| https://github.com/cityofaustin/techstack/issues/4336 | Contacts on guides | [already fixed in master](https://github.com/cityofaustin/janis/pull/746) |
| https://github.com/cityofaustin/techstack/issues/4340 | Official documents get too many docs | already fixed in master |
| https://github.com/cityofaustin/techstack/issues/4347 | Pages using localized slugs | [just hardcoding to slug_en for now](https://github.com/cityofaustin/joplin/pull/713) |
| |  user can reset their password | so for friday we can just manually reset everyone’s passwords and then let them update them after logging in. and have a backlog item for fixing pw reset emails? if that works for everyone |
| https://github.com/cityofaustin/techstack/issues/4346 | filesize not working on documents | |
||Images could not be published|Fixed by CMS_MEDIA fixes in https://github.com/cityofaustin/techstack/issues/4343|
# End to end checklist (check the boxes once we're in prod)

## Information Page
- [ ] Basic Stuff
  - [x] Can be created
  - [x] Can Save, Publish, and Unpublish on Joplin
    - [ ] Save
    - [ ] Publish
    - [ ] Unpublish
  - [ ] Can Preview on Joplin
  - [ ] English content renders on Janis
  - [ ] Spanish content renders on Janis
  - [ ] Contextual Nav is correct
    - [ ] Correct Topics and Departments render
    - [ ] Links to those topics and Departments work
- [ ] Contacts can be added to Joplin, render on Janis

## Service Page
- [ ] Basic Stuff
  - [x] Can be created
  - [x] Can Save, Publish, and Unpublish on Joplin
    - [ ] Save
    - [ ] Publish
    - [ ] Unpublish
  - [ ] Can Preview on Joplin
  - [ ] English content renders on Janis
    - [ ] In preview
    - [ ] When published
  - [ ] Spanish content renders on Janis
    - [ ] In preview
    - [ ] When published
  - [ ] Contextual Nav is correct
    - [ ] Correct Topics and Departments render
    - [ ] Links to those topics and Departments work
- [ ] Contacts can be added to Joplin, render on Janis
- [ ] Steps with Locations render
- [ ] Steps with options render
- [ ] Steps with Dynamic Content render
- [ ] Steps with internal links render

## Guide Page
- [ ] Basic Stuff
  - [x] Can be created
  - [x] Can Save, Publish, and Unpublish on Joplin
    - [ ] Save
    - [ ] Publish
    - [ ] Unpublish
  - [ ] Can Preview on Joplin
  - [ ] English content renders on Janis
  - [ ] Spanish content renders on Janis
  - [ ] Contextual Nav is correct
    - [ ] Correct Topics and Departments render
    - [ ] Links to those topics and Departments work
- [ ] Links for "View this Page on Alpha" work
- [ ] Images can be updated in Joplin and displayed in Janis
- [ ] Contacts
  - [ ] can be added to Joplin
  - [ ] render on Janis

## Form Container
- [ ] Basic Stuff
  - [x] Can be created
  - [x] Can Save, Publish, and Unpublish on Joplin
  - [ ] Can Preview on Joplin
  - [ ] English content renders on Janis
  - [ ] Spanish content renders on Janis
  - [ ] Contextual Nav is correct
    - [ ] Correct Topics and Departments render
    - [ ] Links to those topics and Departments work

## Location Page
- [ ] Basic Stuff
  - [x] Can be created
  - [x] Can Save, Publish, and Unpublish on Joplin
  - [ ] Can Preview on Joplin
  - [ ] English content renders on Janis
  - [ ] Spanish content renders on Janis
- [ ] Links to related services work
- [ ] Images can be updated in Joplin and displayed in Janis

## Official Document Page
- [ ] Basic Stuff
  - [x] Can be created
  - [x] Can Save, Publish, and Unpublish on Joplin
  - [ ] Can Preview on Joplin
  - [ ] English content renders on Janis
  - [ ] Spanish content renders on Janis
  - [ ] Contextual Nav is correct
    - [ ] Correct Topics and Departments render
    - [ ] Links to those topics and Departments work
- [ ] Documents can be added, removed, and reordered
- [ ] Links to documents work on Janis
- [ ] Make sure that Spanish documents localize correctly on Janis 

## Event Page
- [ ] Basic Stuff
  - [x] Can be created
  - [x] Can Save, Publish, and Unpublish on Joplin
  - [ ] Can Preview on Joplin
  - [ ] English content renders on Janis
  - [ ] Spanish content renders on Janis
  - [ ] Contextual Nav is correct
- [ ] Contacts can be added to Joplin, render on Janis
- [ ] It connects to a City Location
- [ ] It connects to a remote Location
- [ ] Fees render

## Topic Page
- [ ] Basic Stuff
  - [x] Can be created
  - [x] Can Save, Publish, and Unpublish on Joplin
  - [ ] Can Preview on Joplin
  - [ ] English content renders on Janis
  - [ ] Spanish content renders on Janis

## Topic Collection Page
- [ ] Basic Stuff
  - [x] Can be created
  - [x] Can Save, Publish, and Unpublish on Joplin
  - [ ] Can Preview on Joplin
  - [ ] English content renders on Janis
  - [ ] Spanish content renders on Janis
- [ ] It still at least renders the title of nested Topics, even if their Top Pages are missing.

## Department Page
- [ ] Basic Stuff
  - [x] Can be created
  - [x] Can Save, Publish, and Unpublish on Joplin
  - [ ] Can Preview on Joplin
  - [ ] English content renders on Janis
  - [ ] Spanish content renders on Janis
- [ ] Images can be updated in Joplin and displayed in Janis
- [ ] Contacts can be added to Joplin, render on Janis

# Misc Janis checks
- [ ] Home Page hero banner image renders. (publisher cms_media issue)
- [ ] Department groups can be added
- [x] Documents can be uploaded

## Users
- [ ] An importer user can reset their password 🐛
- [ ] An imported user can log in
- [ ] An imported user has the permissions they'd expect

## Images
- [x] Images can be uploaded
- [ ] Images can be deleted

## Snippets
- [x] Contacts can be created
- [x] Contacts can be updated
- [x] Contacts can be deleted

**Comment by Niicck** [comment]
4/21/2020 Adding these suggestions by the Content Team:
- Create New Content
- Adding Documents
- Adding Images
- Contacts/Maps/Snippets
- Location Page
- Adding Departments

**Comment by briaguya** [comment]
Testing on https://joplin-pr-import-everything.herokuapp.com/ and https://janis-v3-build-everything.netlify.app/ - 4/23/2020

## Information Page
- [ ] Basic Stuff
  - [x] Can be created
  - [ ] Can Save, Publish, and Unpublish on Joplin
    - [x] Save
    - [x] Publish
    - [ ] Unpublish (this seems to be broken, I think it sends an 'all_pages' command when we unpublish, do we need to use a different react-static command?)
  - [x] Can Preview on Joplin
  - [x] English content renders on Janis
  - [x] Spanish content renders on Janis
  - [x] Contextual Nav is correct
    - [x] Correct Topics and Departments render
    - [x] Links to those topics and Departments work
- [ ] Contacts can be added to Joplin, render on Janis (it's broken [here](https://janis-v3-build-everything.netlify.app/en/health-safety/policing-in-austin/police-feedback-and-records/know-your-rights-when-interacting-police), I'm thinking it's Janis side

**Comment by chiaberry** [comment]
Working on contacts above, also discovered
- [ ] top services on home page not working

**Comment by briaguya** [comment]
Testing on https://joplin-pr-import-everything.herokuapp.com/ and https://janis-v3-build-everything.netlify.app/ - 4/27/2020

## Service Page
- [ ] Basic Stuff
  - [x] Can be created
  - [ ] Can Save, Publish, and Unpublish on Joplin
    - [x] Save
    - [x] Publish
    - [ ] Unpublish (staying published https://github.com/cityofaustin/techstack/issues/4334)
  - [x] Can Preview on Joplin
  - [x] English content renders on Janis
    - [x] In preview
    - [x] When published
  - [ ] Spanish content renders on Janis
    - [x] In preview (works, but could be better - https://github.com/cityofaustin/techstack/issues/4333)
    - [ ] When published (works, but found an issue with steps https://github.com/cityofaustin/techstack/issues/4332)
  - [x] Contextual Nav is correct
    - [x] Correct Topics and Departments render
    - [x] Links to those topics and Departments work
- [x] Contacts can be added to Joplin, render on Janis
- [x] Steps with Locations render [verified here](https://janis-v3-build-everything.netlify.app/en/housing-utilities/recycling-trash-and-compost/household-waste/hazardous-waste-dropoff/)
- [x] Steps with options render [verified here](https://janis-v3-build-everything.netlify.app/en/health-safety/health-prevention/disease-prevention/get-food-handler-training-and-food-manager-certificate)
- [x] Steps with Dynamic Content render [recollect here](https://janis-v3-build-everything.netlify.app/en/housing-utilities/recycling-trash-and-compost/household-waste/bulk-item-pickup)
- [x] Steps with internal links render [step 6 here](https://janis-v3-build-everything.netlify.app/en/health-safety/health-prevention/disease-prevention/bring-your-mobile-food-unit-to-your-inspection-appointment/)

**Comment by briaguya** [comment]
Testing on https://joplin-pr-import-everything.herokuapp.com/ and https://janis-v3-build-everything.netlify.app/ - 4/28/2020

## Guide Page
- [ ] Basic Stuff
  - [x] Can be created
  - [ ] Can Save, Publish, and Unpublish on Joplin
    - [x] Save
    - [x] Publish
    - [ ] Unpublish (known issue https://github.com/cityofaustin/techstack/issues/4334)
  - [x] Can Preview on Joplin
  - [x] English content renders on Janis
  - [ ] Spanish content renders on Janis (updated https://github.com/cityofaustin/techstack/issues/4332 to include a link to a 404ing guidee)
  - [x] Contextual Nav is correct
    - [x] Correct Topics and Departments render
    - [x] Links to those topics and Departments work
- [x] Links for "View this Page on Alpha" work
- [ ] Contacts
  - [x] can be added to Joplin
  - [ ] render on Janis https://github.com/cityofaustin/techstack/issues/4336

**Comment by briaguya** [comment]
Testing on https://joplin-pr-import-everything.herokuapp.com/ and https://janis-v3-build-everything.netlify.app/ - 4/28/2020 (updated import everything to always trigger a rebuild instead of all pages for now)

## Form Container
- [x] Basic Stuff
  - [x] Can be created
  - [x] Can Save, Publish, and Unpublish on Joplin
  - [x] Can Preview on Joplin
  - [x] English content renders on Janis
  - [x] Spanish content renders on Janis
  - [x] Contextual Nav is correct
    - [x] Correct Topics and Departments render
    - [x] Links to those topics and Departments work

**Comment by briaguya** [comment]
Testing on https://joplin-pr-import-everything.herokuapp.com/ and https://janis-v3-build-everything.netlify.app/ - 4/28/2020 (updated import everything to always trigger a rebuild instead of all pages for now)

## Location Page
- [x] Basic Stuff
  - [x] Can be created
  - [x] Can Save, Publish, and Unpublish on Joplin
  - [x] Can Preview on Joplin
  - [x] English content renders on Janis
  - [x] Spanish content renders on Janis
- [x] Links to related services work

**Comment by briaguya** [comment]
## Official Document Page
- [ ] Basic Stuff
  - [x] Can be created
  - [ ] Can Save, Publish, and Unpublish on Joplin
  - [ ] Can Preview on Joplin (found issue https://github.com/cityofaustin/techstack/issues/4340)
  - [ ] English content renders on Janis (found issue https://github.com/cityofaustin/techstack/issues/4340)
  - [ ] Spanish content renders on Janis (found issue https://github.com/cityofaustin/techstack/issues/4340)
  - [x] Contextual Nav is correct
    - [x] Correct Topics and Departments render
    - [x] Links to those topics and Departments work
- [x] Documents can be added, removed, and reordered
- [x] Links to documents work on Janis
- [ ] Make sure that Spanish documents localize correctly on Janis 
  - [ ] Ref: https://github.com/cityofaustin/techstack/issues/4076

**Comment by briaguya** [comment]
Testing on https://joplin-pr-import-everything.herokuapp.com/ and https://janis-v3-build-everything.netlify.app/ - 4/29/2020

## Official Document Page
- [x] Basic Stuff
  - [x] Can Save, Publish, and Unpublish on Joplin
  - [x] Can Preview on Joplin
  - [x] English content renders on Janis
  - [x] Spanish content renders on Janis
  - [x] Contextual Nav is correct
    - [x] Correct Topics and Departments render
    - [x] Links to those topics and Departments work
- [x] Documents can be added, removed, and reordered
- [x] Links to documents work on Janis
- [x] Make sure that Spanish documents localize correctly on Janis

**Comment by briaguya** [comment]
Testing on https://joplin-pr-import-everything.herokuapp.com/ and https://janis-v3-build-everything.netlify.app/ - 4/29/2020

## Event Page
- [ ] Basic Stuff
  - [x] Can be created
  - [x] Can Save, Publish, and Unpublish on Joplin
  - [x] Can Preview on Joplin
  - [x] English content renders on Janis
  - [ ] Spanish content renders on Janis (https://github.com/cityofaustin/techstack/issues/4347)
  - [x] Contextual Nav is correct
- [x] Contacts can be added to Joplin, render on Janis
- [x] It connects to a City Location
- [x] It connects to a remote Location
- [x] Fees render

**Comment by briaguya** [comment]
Testing on https://joplin-pr-import-everything.herokuapp.com/ and https://janis-v3-build-everything.netlify.app/ - 4/29/2020

## Topic Page
- [x] Basic Stuff
  - [x] Can be created
  - [x] Can Save, Publish, and Unpublish on Joplin
  - [x] Can Preview on Joplin
  - [x] English content renders on Janis
  - [x] Spanish content renders on Janis

**Comment by briaguya** [comment]
Testing on https://joplin-pr-import-everything.herokuapp.com/ and https://janis-v3-build-everything.netlify.app/ - 4/29/2020

## Topic Collection Page
- [x] Basic Stuff
  - [x] Can be created
  - [x] Can Save, Publish, and Unpublish on Joplin
  - [x] Can Preview on Joplin
  - [x] English content renders on Janis
  - [x] Spanish content renders on Janis
- [x] It still at least renders the title of nested Topics, even if their Top Pages are missing.

**Comment by briaguya** [comment]
Testing on https://joplin-pr-import-everything.herokuapp.com/ and https://janis-v3-build-everything.netlify.app/ - 4/29/2020

## Department Page
- [ ] Basic Stuff
  - [x] Can be created
  - [x] Can Save, Publish, and Unpublish on Joplin
  - [x] Can Preview on Joplin
  - [x] English content renders on Janis
  - [x] Spanish content renders on Janis
- [ ] Images can be updated in Joplin and displayed in Janis (publisher cms_media issue)
- [x] Contacts can be added to Joplin, render on Janis

**Comment by briaguya** [comment]
Testing on https://joplin-pr-import-everything.herokuapp.com/ and https://janis-v3-build-everything.netlify.app/ - 4/29/2020

# Misc Janis checks
- [ ] Home Page hero banner image renders. (publisher cms_media issue)
- [x] Department groups can be added
- [x] Documents can be uploaded

## Users
- [ ] An importer user can reset their password (I can't even get the email on prod though...)
- [ ] An imported user can log in
- [x] An imported user has the permissions they'd expect

## Images
- [x] Images can be uploaded, deleted
- [ ] Images render on pages (publisher cms_media issue)
 - [ ] Location Page
 - [ ] Guide Page
 - [ ] Department Page

## Snippets
- [x] Contacts can be created, updated, deleted

**Comment by briaguya** [comment]
Verifying pages on import/build everything - 4/30/2020

This run covers all pages in the mobile food vendor permit guide, as well as the pages in the pools guide. This also covers all service pages that aren't in a guide.

- [x] Mobile food vendor permit guide
  - [x] Documents for mobile food vendors in Austin
  - [x] Businesses required to get a mobile food vendor permit
  - [x] Mobile food vendor permit types and fees
  - [x] Get a central preparation facility
    - [ ] The default url for this (used by guide) is under disease prevention, on v2 it was food business permits
  - [x] Get food handler training and a food manager certificate
  - [x] Mobile food vendor pre-application checklist
  - [x] Prepare your mobile food vendor permit application
  - [x] Apply for a mobile food vendor operational permit
  - [x] Fire safety checklist for mobile food vendors
  - [x] Bring your mobile food unit to your inspection appointment
  - [x] Requirements to safely operate your mobile food business
  - [x] Renew your mobile food vendor permit
  - [x] Report changes to your mobile food business

- [ ] Pools, spas, public interactive water features and fountains permitting guide
  - [ ] Documents for the pool permitting process
    - [ ] this was live but didn't have a url, so we were getting a 404, it's just a draft now and the previews match
    - [ ] external link to doc in rich text, updated to use prod bucket url, verify in prod
      - [ ] since these aren't "official docs" I don't think they've been imported at all
  - [ ] Pool permit types and fees
    - [ ] this was live but didn't have a url, so we were getting a 404, it's just a draft now and the previews match
    - [ ] the change of ownership link is using placeholder at the moment (issues with live/draft links)
  - [x] Helpful services and tools for getting your pool permitted
    - [ ] this was live but didn't have a url, so we were getting a 404, it's just a draft now and the previews match
  - [x] Find your pool, spa, PIWFF or fountain’s jurisdiction
    - [ ] this was live but didn't have a url, so we were getting a 404, it's just a draft now and the previews match
  - [ ] What to expect if your pool receives violations
    - [ ] this was live but didn't have a url, so we were getting a 404, it's just a draft now and the previews match
    - [ ] Something is going on in here with contacts/locations
  - [ ] Get a refund for your pool, spa, and PIWFF permitting fees
    - [ ] this was live but didn't have a url, so we were getting a 404, it's just a draft now and the previews match
    - [ ] external link to doc in rich text, updated to use prod bucket url, verify in prod
  - [ ] Pre-plan review checklist for new or remodeled pools, spas, and PIWFFs
    - [ ] this was live but didn't have a url, so we were getting a 404, it's just a draft now and the previews match
    - [ ] can't update, issues saving due to long title
  - [ ] Submit a plan review application for your new or remodeled pool, spa, public interactive water feature or fountain
    - [ ] this was live but didn't have a url, so we were getting a 404, it's just a draft now and the previews match
    - [ ] external link to doc in rich text, updated to use prod bucket url, verify in prod
      - [ ] link not updated, issues saving due to long title
  - [x] Get your pool plans reviewed by the Watershed, Development Services and Fire departments
    - [ ] this was live but didn't have a url, so we were getting a 404, it's just a draft now and the previews match
  - [ ] Prepare operational permit application materials for your pool, spa, public interactive water feature or fountain
    - [ ] this was live but didn't have a url, so we were getting a 404, it's just a draft now and the previews match
    - [ ] external link to doc in rich text, updated to use prod bucket url, verify in prod
      - [ ] link not updated, issues saving due to long title
  - [ ] Prepare for a certificate of occupancy inspection for your pool, spa, public interactive water feature or fountain
    - [ ] this was live but didn't have a url, so we were getting a 404, it's just a draft now and the previews match
    - [ ] external link to doc in rich text, updated to use prod bucket url, verify in prod
      - [ ] link not updated, issues saving due to long title
  - [x] Submit your operational permit and certificate of occupancy inspection applications for your pool
    - [ ] this was live but didn't have a url, so we were getting a 404, it's just a draft now and the previews match
  - [x] Schedule a pre-opening certificate of occupancy inspection for your pool, spa, public interactive water feature or fountain
    - [ ] this was live but didn't have a url, so we were getting a 404, it's just a draft now and the previews match
  - [x] Requirements to safely operate your pool, spa, public interactive water feature or fountain
    - [ ] this was live but didn't have a url, so we were getting a 404, it's just a draft now and the previews match
    - [ ] can't update, issues saving due to long title
  - [x] Renew your pool, spa, public interactive water feature or fountain’s operational permit
    - [ ] this was live but didn't have a url, so we were getting a 404, it's just a draft now and the previews match
  - [x]  Report changes to pool, spa, public interactive water feature or fountain
    - [ ] this was live but didn't have a url, so we were getting a 404, it's just a draft now and the previews match
  - [ ] Apply for a change of ownership inspection for your pool, spa, public interactive water feature or fountain
    - [ ] this was live but didn't have a url, so we were getting a 404, it's just a draft now and the previews match
    - [ ] external link to doc in rich text, updated to use prod bucket url, verify in prod

- [ ] Community garden permitting guide
 - [ ] We don't currently have any pages in here


- [ ] Service pages (not in guides)
  - [x] Get your bulk items collected
  - [ ] Help prevent diabetes in your community
   - [ ] notes: matches https://alpha.austin.gov/en/preview/services/UGFnZVJldmlzaW9uTm9kZTozNjg4, not https://alpha.austin.gov/en/health-safety/health-prevention/disease-prevention/help-prevent-diabetes-in-your-community/
  - [x] Find work as a day laborer
  - [x] Hire a day laborer
  - [x] Drop off household hazardous waste and other recyclables
  - [x] Pick up free paint and other household items
  - [x] Test out how to use a service page
  - [ ] Serve on the Community Police Review Commission
    - [ ] external link to doc in rich text, updated to use prod bucket url, verify in prod
  - [x] Get basic services at neighborhood centers
  - [x] Get a copy of your immunization record
  - [x] Handle a parking ticket
  - [x] Look up your trash, recycling, and compost pickup days
  - [x] Report smoking or vaping in a public place
  - [ ] File a citizen complaint
    - [ ] external link to doc in rich text, updated to use prod bucket url, verify in prod
  - [x] Get a birth or death certificate
  - [ ] Get breastfeeding support
    - [ ] Something is going on in here with contacts/locations
  - [x] Testing (looks like it's just a page with the title "Testing")
  - [x] Request court records
  - [x] Get help with rent and utility payments
  - [x] Thank an Austin police officer
  - [x] File a complaint about an Austin police officer
  - [x] Get immunizations for you and your family
  - [x] Get free HIV testing
  - [x] Prepare for public health emergencies
  - [x] Find free condoms and learn other ways to prevent HIV
  - [x] Attend a fall prevention class
  - [x] Plan a smoke-free event
  - [ ] Get a community garden permit
    - [ ] the soil kitchen link is using placeholder at the moment (it was hardcoded as an external link to a preview in v2)
  - [x] Recycle your Christmas tree
  - [x] Test your soil at the Soil Kitchen
  - [x] test map padding (so this exists)
  - [x] Take a tuberculosis (TB) test
  - [x] Recycle your batteries
  - [ ] Get your home composting rebate
    - [ ] the chicken keeping rebate link is using placeholder at the moment (it was hardcoded as an external link to a preview in v2)
  - [x] Get tested for sexually transmitted infections
  - [x] Keep your permit valid
    - [ ] this was live but didn't have a url, so we were getting a 404, it's just a draft now and the previews match
  - [x] Get ready for curbside compost
  - [x] Get a water tap
  - [x] Prep your garden for water
  - [x] Fund your neighborhood project
  - [x] Is your garden eligible?
  - [x] Request a license agreement
  - [x] Request a compost class
  - [x] Plan your garden
  - [x] Request a dead animal pickup
  - [x] Get your zero waste rebate
  - [x] Reduce food waste at your business
  - [x] Get your chicken keeping rebate
  - [x] Sustain your business
  - [x] Set out your leaves, grass, and branches for pickup
  - [x] Get a mobile food vendor permit (looks like just a service page with a title)

**Comment by briaguya** [comment]
topic pages should be good now

- [x] Topic pages
  - [x] Community Police Review Commission
  - [x] Get help paying bills
  - [x] Police oversight and feedback
  - [x] Court records and documents
  - [x] Household waste
  - [x] Help finding work
  - [x] Kids and family resources
  - [x] Food business permits
  - [x] Opportunities for teens
  - [x] Funding, grants, and rebates
  - [x] Workforce development and hiring
  - [x] Disease prevention
    - [x] Measles in Austin (info page)
  - [x] Health classes and resources
  - [x] Disaster preparedness
  - [x] Birth and death certificates
  - [x] Recycling and reuse
  - [x] Compost and food waste
  - [x] Chronic disease prevention
  - [x] Injury prevention

**Comment by briaguya** [comment]
location pages should be good now

- [x] Location pages
  - [x] APH online clinic test
  - [x] Carver Branch Library
  - [x] Downtown Austin Community Court
  - [x] First Workers Day Labor Center
  - [x] Far South Austin Clinic
  - [x] Rebekah Baines Johnson (RBJ) Health Center
  - [x] Main Courthouse, Austin Municipal Court
  - [x] Jaime Padron Substation, Austin Municipal Court
  - [x] Office of Police Oversight
  - [x] Office of Vital Records
  - [x] East Austin Neighborhood Center
  - [x] St. John Community Center
  - [x] South Austin Neighborhood Center
  - [x] Environmental Health Services Division
  - [x] Rosewood-Zaragosa Neighborhood Center
  - [x] Montopolis Neighborhood Center
  - [x] Blackland Neighborhood Center
  - [x] Mom's Place Lactation Support Center
  - [x] Recycle & Reuse Drop-off Center

**Comment by briaguya** [comment]
- [ ] Topic collections
  - [x] Policing in Austin
  - [x] Pay utility bills and rent
  - [x] Records and documents
  - [x] Health and prevention
  - [x] Business permits and licenses
  - [x] Job resources (we had 2, one with job-resources as a slug and one with business-resources as a slug, now we only have one)
  - [x] Business resources
  - [x] Financial resources
  - [x] test
  - [x] Police oversight
  - [x] Disaster and safety relief
  - [x] Health records and certificates
  - [x] Recycling, trash, and compost

**Comment by Niicck** [comment]
### Form Containers

- [ ] 7 additional forms would need to be imported
- [ ] New drafts made today on several forms

- [x] Apply to serve on the Community Police Review Commission
- [x] Basic traffic deferral
- [x] Report smoking or vaping in a public place
  - [ ] Updated today to include a new Topic
- [x] Request a Day Laborer
- [x] Request an online municipal court hearing
- [x] Request judicial information
- [x] Waive your right to a jury trial

### Department Pages
- [x] Austin Public Health
  - [x] Top Service links work
  - [x] Related Links work
- [x] Office of Police Oversight
  - [x] Department Director Headshot works
  - [x] Banner Image works
- [x] Austin Resource Recovery
  - [x] Contact has location attached, unlike prod. feature?
- [x] Municipal Court
  - [x] Contact has location attached, same as prod.
- [ ] Parks and Recreation
  - [ ] Community gardens external link hardcoded to preview URL in prod?
  - [ ] If we preserve it, it'll just have to be a manual change when we switch to production.
- [x] Real Estate Services

**Comment by chiaberry** [comment]
### Information Page
checked Live pages: 
only issues found were ones previously mentioned (contextual nav & location address commas)
- [ ] "Complaint investigation process"
- [ ]  "Get free help to quit tobacco"
- [ ]  "Privacy policy for Alpha.Austin.gov"
- [ ] "Fire safety checklist for mobile food vendors"
- [ ]  "Measles in Austin"
- [ ]  "Requirements to safely operate your mobile food business"
- [ ]  "Help prevent diabetes in your community"
- [ ]  "How we store and use your data"
- [ ] "WIC benefits"
- [ ] "Community youth development in Dove Springs"
- [ ] "Mobile food vendor permit types and fees"
- [ ] "Crypto and other waterborne diseases"
- [ ] "Breastfeeding support"
- [ ] "Participate in research with the City of Austin"
- [ ] "Smoking in public places"
- [ ]  "Know your rights when interacting with the police"
- [ ] "Documents for mobile food vendors in Austin"
- [ ] "Businesses required to get a mobile food vendor permit"
- [ ] "Mobile food vendor pre-application checklist"

**Comment by briaguya** [comment]
made test pages to check the boxes, they have all been deleted so we can add "Can be deleted" to all those content types
