### ISSUE TITLE
Search: labeling content

### ISSUE THREAD

**Issue by chase-vert** [cityofaustin/techstack#4217]
@toribr and I reviewed some examples together and noted the way some results lists labeled or displayed content depending on the type. We think this could be very helpful in the future, so let's figure out how and when to do it.

# User story
### As a resident, I want more context in the results list, so that I can find the page/information I'm looking for.

# To-do
- [ ] Create a table with all content types and/or data that could appear in a search result
- [ ] Research best practices and user research about how to make search more relevant, and successful for residents
- [ ] Design: work with @toribr to think through what to label and how

# Examples
<img width="1008" alt="Screen Shot 2020-03-26 at 11 22 41 AM" src="https://user-images.githubusercontent.com/7027270/77691387-ce850380-6f72-11ea-87d1-b924847c796e.png">
<img width="998" alt="Screen Shot 2020-03-26 at 11 24 40 AM" src="https://user-images.githubusercontent.com/7027270/77691388-cf1d9a00-6f72-11ea-830d-6eb3cdd9f01d.png">
<img width="1062" alt="Screen Shot 2020-03-26 at 11 24 44 AM" src="https://user-images.githubusercontent.com/7027270/77691389-cf1d9a00-6f72-11ea-970b-b08e9f9fe4b8.png">
<img width="971" alt="Screen Shot 2020-03-26 at 11 24 47 AM" src="https://user-images.githubusercontent.com/7027270/77691391-cfb63080-6f72-11ea-9257-af7912802c0f.png">

**Comment by chase-vert** [comment]
Duplicate of: https://github.com/cityofaustin/techstack/issues/4228
