### ISSUE TITLE
Incorporate feedback from OPO on about page for the CPRC

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#4261]
### User story
As a resident concerned about police oversight, I want to be able to know about what the commission is, who its members are, and what the commission is working on, so that I have a sense of what the City and civilians are doing to address policing in Austin.

### Timeline
This page and the CPRC topic page will need to be published the week the commissioner appointments are announced, which has shifted to late August to mid-September. Standing by for updates on that. 

### Tasks

- [x] Get feedback, edits from OPO. (Round 1)
- [x] Incorporate feedback and edits. 
- [x] Send to OPO for another round of review. (Round 2) 
- [x] Incorporate any edits. 
- [x] When OPO contacts us about publishing, ask if any other content needs to be included. 
- [x] Communicate w/ OPO about content to add to the [About CPRC page](https://joplin.herokuapp.com/admin/pages/163/edit/#tab-content) as the information becomes available: 
- Commissioners' names and email addresses (ETA late August to mid-September)
- Commission bylaws (ETA October) 

When it's ready for publishing, we'll need to do a quick proofread with at least one other pair of eyes:
- [ ] Send to content teammate 1 for review. @InaraFernandez can you give it a once-over? 
- [ ] Incorporate those edits. 
- [ ] Send to content teammate 2 for review. 
- [ ] Incorporate those edits. 

More content: see #4721

**Comment by Jo-Dwyer** [comment]
Is this still blocked @InaraFernandez and @srigdon or can this be sent to a teammate for review?

**Comment by srigdon** [comment]
@Jo-Dwyer Not blocked, just waiting on information to become available. I adjusted to Sprint 63. Let's keep in contact w/ OPO on this.

**Comment by InaraFernandez** [comment]
This will probably wrap up by next Tuesday.
