### ISSUE TITLE
Dev-Design Sync 4/21/20

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/techstack#4271]
From dev:
- [x] What do we want URL links to be? Is there a specific instance we prefer (under department pages, which topic collections etc?)

From Design:
- [x] Joplin v3 implications on feature design workflow (future thinking, ongoing convo)
- [x] what does v3 mean to design?
- [x] Event on servic, info, location pages dev issue (ref dev issues #4215 #4214  #4235)
- [x] the state of Joplin UI - where are we and what's happening
- [ ] media release #4234 #4243 (hold until imminent)
- [ ] publish queue #4236 (hold until imminent)
