### ISSUE TITLE
Implement Edit Service Page View components in Storybook

### ISSUE THREAD

**Issue by mateoclarke** [cityofaustin/techstack#431]
UPDATED 6/20/18

Sketch file: https://drive.google.com/open?id=1RgorDzI74IOjz4d1FIdk7nge2XhgNgVb

![edit service page w specs](https://user-images.githubusercontent.com/3790067/41668784-cbae273a-7475-11e8-92bc-a0cf68a83b25.png)

## Rough List of Components:

- [ ] `<GlobalHeader/>` also listed in #430 
- [ ] `<PageHeader/>` (1) - also listed in #430 but different usage here
  - page header should be sticky
  - action buttons slightly differ b/e publisher & author
  - `<ShareButton/>`
  - `<SaveButton/>`
    - has a secondary menu with a `<RevisionHistoryButton/>`
- [ ] Form validation that all required field are minimally set (1)
- [ ] `<LeftSidebarNavigation/>` also listed in #430 
- [ ] `<PageHeader/>` "Edit Service Page" title (variation from whats listed in #430)
- [ ] `<EditBreadcrumb/>` (2) - title and topic selection
- [ ] `<SelectBannerImage/>` (3)
  - has hideable help text section
  - remove button
  - _what does this look like when no banner image has been uploaded yet?_
- [ ] `<EditServiceSteps>` (4)
  - min 2 steps, can remove step 3 and beyond
  - _can you reorder steps?_
  - `<AddServiceStep>`
- [ ] Add apps section (5)
  - [ ] `<EmbededApp/>`
  - [ ] `<AddEmbededApp/>`
    - _does the add app selection box appear as a modal?_
- [ ] Free text field (6)
  - [ ] <TextArea/> (8)
    - HTML formatting availble TBD
   - minimum character limit with error state
    - _what type of formatting options are we going to give? hyperlinks? bold, italic, etc?_
- Meta fields section
  - shaded background for items that don't get rendered to the page
  - [ ] `<TextArea/>` for page description
  - [ ] `<TextInput/>` for shortened URL alias
  - [ ] `<AddTags/>` (9) for keyword & phrase tagging
 - [ ] Successful save screen affirmation
  - _does this appear as a modal?_
- Preview sidebar will come later in #417

**Comment by mateoclarke** [comment]
@toribr, yes, there is an upload limit. 😞 

We've been saving larger assets to Google Drive. Celine added a ["Design" section with a bunch of links to the Janis README](https://github.com/cityofaustin/janis#-design). We could add a similar section to the Pearl README too.

**Comment by toribr** [comment]
FYI, my bad, but I just noticed that there is a tagging functionality in images. If it's not too late,  rather than recreate the wheel, it's cool to use that same interaction pattern on the service page. (however, there would be a min # of tags (3) and a max # amount of tags (8?).
![screen shot 2018-06-28 at 9 52 05 am](https://user-images.githubusercontent.com/3790067/42042147-20615a6a-7ab9-11e8-8f99-6bce9cd39d48.png)

**Comment by mateoclarke** [comment]
Closing as we've opted to use Wagtail CMS and not decouple our Author Interface at this time.
