### ISSUE TITLE
Modal: "create content" enhancements 💅 

### ISSUE THREAD

**Issue by chase-vert** [cityofaustin/techstack#4314]
# Goal
Background: As we add more content types this modal container is less and less easy to use. Let's figure out what's needed to 
- have better flexibility with more content types
- support onboarding new users with little to no training 
- think about how to make topics and topic collection types more visible

## To-do
- [x] Review existing implementation 
- [x] define improvements
- [x] Import progress into Abstract from the last pass
- [x] Iterate on existing designs
- [x] Review with @toribr  during Thursday pin-up
- [x] Update Bob's links in his dev issue #4008 

**Links**
- Abstract branch [Modal: create content enhancements](https://share.goabstract.com/1ae7408d-9eda-488f-b2cc-10a7234d77a4)
- 📌 Pin up ∙ April 28 [abstract collection](https://share.goabstract.com/2cb8caf7-c1dc-49c9-b32d-74bc254e479e)
---
## Related issues
- Joplin UI: Create content model & Contact modal [#4008](https://github.com/cityofaustin/techstack/issues/4008) `Dev issue` 
- Auto-generate "create new content" modal [#2489](https://github.com/cityofaustin/techstack/issues/2489)
>See #2466. Would be nice if the options within the "create new content" modal dynamically generated based on content models.
- Educate users in the "create topic" and "create topic collection" modals [#4087](https://github.com/cityofaustin/techstack/issues/4087) `Content issue` 
>As an author in Joplin, I want to know how to write titles for topic collections and topics that connect residents to what they're looking for. I also want to learn more about the IA when I create these containers, so I know how to organize my content in an easily navigable, searchable way.

**Comment by chase-vert** [comment]
# Round 2
https://share.goabstract.com/2cb8caf7-c1dc-49c9-b32d-74bc254e479e
