### ISSUE TITLE
Dev-Design Sync 4/28/2020

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/techstack#4318]
from dev:
* questions about dept permissions (https://docs.google.com/spreadsheets/d/1zE_Y806MlCli1aSkzIbXTzCTA01KWSReLGrJ7b5sUYU/edit#gid=0)
* favicon (we're more than just wagtail!)
* style guide anchor links https://github.com/cityofaustin/techstack/issues/4326
* Site Search Update with Bob

#From design: 
- [x] media release #4234 #4243 (hold until imminent)
Outstanding things to cover, may or may not be discussed, depending on timing:
- [ ] publish queue #4236 (hold until imminent)
- [ ] alerts overview #4259 how home page content control might work and alerts as snippets
