### ISSUE TITLE
Draft a content drafting and publishing checklist

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#4345]
### User story
As a content author who's attended a Funshop, I want to quickly ensure I'm drafting and publishing resident-focused and service-oriented content that meets [WCAG 2.1](https://www.w3.org/WAI/standards-guidelines/wcag/glance/). 

### To dos: 

- [ ] Draft an [accessible content creation checklist](https://docs.google.com/document/d/1X1BOn0_8-TLKqStKvVZZDGC0XOz12X8uiyt4yNVbabU/edit#), organized by task and content type, for upcoming mini-Funshops (start with [Content pre-publish checklist](https://docs.google.com/document/d/17ebdnA61_chy4S8p-meRoVLogus886-Y5N1qi6lp9kw/edit), see also #4316): 
- [ ] - Official documents page 
- [ ] - Information page
- [x] - Service page
- [ ] - Department page 
- [ ] Refer to [How to Meet WCAG (Quick Reference)](https://www.w3.org/WAI/WCAG21/quickref/) for tips to add in a task-based, happy path way. 
- [ ] Same task for: https://webaim.org/projects/screenreadersurvey8/ 
- [x] Review Service Access work to inform checklist: https://github.com/cityofaustin/serviceaccess/issues/108 
- [ ] Share draft with content team at pinup. 
- [ ] Add to #4230.

**Comment by srigdon** [comment]
We got our wires crossed with this issue and #4534. So we're talking it through in #4617.
