### ISSUE TITLE
dev-design sync 05-12-20

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/techstack#4381]
Agenda
- [ ] Permissions:
  - [ ] https://github.com/cityofaustin/techstack/issues/4097 How strict should "search" permissions be. Should users not be able to search for or view pages that aren't in their department?
  - [ ] https://github.com/cityofaustin/techstack/issues/4203 Page Pickers. Can you pick pages not in your department? Can you "view" those pages that you've picked?
  - [ ] Can users view pages that aren't in their department. But we just restrict the UI so they have to know what they're looking for? (Ex: page picker pages).
- [ ] Next steps for news. Big page for news by department, etc.

From design
- [ ] Global nav
  - [x] Question from devs: Are these the right issues for this: https://github.com/cityofaustin/techstack/issues/4258 and https://github.com/cityofaustin/techstack/issues/3901 ?
- [ ] #4389 alpha messaging on search
- [x] Content type for next sprint no longer necessary
- [x] Official documents joplin sketches (scoping)
- [x] Official documents and search (which is faster - adding OPO documents to search, or adding filter by department to search?)
