### ISSUE TITLE
Create a checklist to QC before publication

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#4534]
### As a content publisher I want an interactive, checkable checklist of qualities my page before publication so that I can document that I've checked it for readability, SME accuracy, and translation.

**Is your feature request related to a problem? Please describe.**
As a content publisher just learning how to use the new standards for web content, I want to be sure that I hit all the marks for readability before I hit publish.

**Describe the solution you'd like**
A checkable checklist?

**Describe alternatives you've considered**
A readability API

**Additional context**

**Comment by gabrielaperezdelaosa** [comment]
Just a draft based on @srigdon 's [doc ](https://docs.google.com/document/d/17ebdnA61_chy4S8p-meRoVLogus886-Y5N1qi6lp9kw/edit#) to get the ball rolling.

- [ ] This page is necessary and fact-checked
- [ ] This page is specific to only one user-need, not a catch-all or an FAQ.
- [ ] Title begins with a verb
- [ ] Page description lets the reader know in plain language what this page is for/what they can do here. Contains key words. 
- [ ] Service-oriented rather than department-oriented language
- [ ] Content is as short as I can make it
- [ ] Content has no long paragraphs or lists that aren't bulleted
- [ ] Content has been put through the Hemingway app and is below an 8th grade level or as low as possible
- [ ] Content is as evergreen as possible (does not include information likely to change) 
- [ ] Hyperlink text is clear and actionable (avoid "Click here") 
- [ ] All links on the page go to trustworthy sources
- [ ] No PDFs or other downloadable files have been linked where the information could've been built into the page instead
- [ ] There is alt-text for any images
- [ ] SEO????

**Comment by Jo-Dwyer** [comment]
I'm being nit-picky, but how do we define "necessary" @gabrielaperezdelaosa?

**Comment by Jo-Dwyer** [comment]
@toribr FYI

**Comment by gabrielaperezdelaosa** [comment]
> I'm being nit-picky, but how do we define "necessary" @gabrielaperezdelaosa?

I don't think that's picky...totally valid. I got that straight from the previously-created list and I think it was trying to get authors to think about minimizing content rather than using the website as a filing cabinet. Maybe we can think of a better way to phrase it? Or, the list is pretty long, it could certainly stand to be shortened. @Jo-Dwyer

**Comment by easherma** [comment]
https://github.com/vixdigital/wagtail-readinglevel <--just FYI, and I've mentioned this before, but there are def ways we can expose readability scores directly in the author interface

**Comment by srigdon** [comment]
I took Gabi's draft checklist above and fleshed it out a bit into the [draft here](https://docs.google.com/document/d/1X1BOn0_8-TLKqStKvVZZDGC0XOz12X8uiyt4yNVbabU/edit#heading=h.rxc3h0210x67). We're talking more about this in #4617.

**Comment by srigdon** [comment]
The [fleshed out draft](https://docs.google.com/document/d/1X1BOn0_8-TLKqStKvVZZDGC0XOz12X8uiyt4yNVbabU/edit#heading=h.p8dukk9uvocb) just needs another round or two of review. Potentially we could talk about this in pinup? @ablangworthy27

**Comment by gabrielaperezdelaosa** [comment]
@Jo-Dwyer pinging you cause I'd love to close out this issue.

**Comment by Jo-Dwyer** [comment]
@toribr can we add this checklist to the Joplin interface?

**Comment by toribr** [comment]
@Jo-Dwyer We need to resolve how to get the style guide integrated, period. I'll put this issue on design's plate for next sprint.
