### ISSUE TITLE
Official doc (single view): date [CRITERIA]

### ISSUE THREAD

**Issue by chase-vert** [cityofaustin/techstack#4772]
## Background
We recently introduced the official doc (single view), and left off the `date`; this issue corrects that by adding the date.

## To-do
- [x] Add `date` information as an overline above the `document title`
  - [x] Desktop
  - [ ] Tablet 
  - [x] Mobile 
- [x] Dates will need `Spanish` language support for month names

**Links**
https://share.goabstract.com/8ef75f24-ab78-4061-bcf5-44177616247a

## Acceptance criteria
- [ ] Implementation matches mocks
- [x] All responsive sizes
   - [x] Desktop
  - [x] Tablet 
  - [x] Mobile 
- [x] Translation: `Spanish` month names

**Comment by chase-vert** [comment]
@jairPineros this small issue is ready for dev. There isn't a lot in the way of criteria since this is just adding the document date above the page heading. Let me know if more criteria is needed.

**Comment by chiaberry** [comment]
https://janis-v3-4772-single-doc.netlify.app/en/police-oversight/memo-protest-complaints/

**Comment by jairPineros** [comment]
I see the line date above of the title and the corresponding translations, so this issue passes. But I have a quick question before I give the green light:

@chase-vert and @chiaberry I'm checking the abstract comps with alpha and I see that the title in the comps have a format "title, Month year"  Is this a hard requirement for the titles? because I don't all the titles having that format
