### ISSUE TITLE
Search v2: clean-up

### ISSUE THREAD

**Issue by chase-vert** [cityofaustin/techstack#4774]
# Overview
Dev is working on the next set of enhancements for search, so let's take a look at what we'll need to do to support this functionality. 

## To-do
- [x] List out all interactions associated with search
  - [x] Global nav component
  - [x] Search page
- [x] Highlight keyword matches in page description (if available) https://github.com/cityofaustin/techstack/issues/4837
- [x] Date pickers: https://github.com/cityofaustin/techstack/issues/4773

# Search flows
### Global nav search button and field
Search button
- States
  - Default
  - Hover
  - Active (open)
- Interactions
  - Click: opens input field, slides out towards the left
  - focus state around the input field
- Keyboard interactions 
  - when focus state is on the `text input field`, pressing `enter` takes the user to the search page
  
### Search page
Search button
- States
  - Default
  - Hover

Interactions
- Clicking on `Search` submits the query, and returns the result beneath the header

# Issues detected
### Global nav: search term visible after hitting `back`
After submitting a search from the global nav component, if the users presses the `back` button, the search term is still visible, but the search function appears to be in the `default state`. 
![Screen Shot 2020-08-20 at 8 54 09 AM](https://user-images.githubusercontent.com/7027270/90779066-05153f00-e2c3-11ea-8ac4-ec81b03ad2ff.png)
- [ ] **Expected behavior**: after a user has submitted a search in the global nav, if they press the `back` button, on the next page the search component should return to its default state, with no visible input field text

### Global nav: page height issue
Connected to the issue above, after the user presses the `back` button, the page doesn't reload to the very top of the page height. 
![Screen Shot 2020-08-20 at 9 00 06 AM](https://user-images.githubusercontent.com/7027270/90779520-8bca1c00-e2c3-11ea-91b4-9ea38d997a47.png)
- [ ] **Expected behavior**: Page refreshes and the viewport is restored to the very top of the page, i.e. no part of the `alert banner` is cutoff by a few pixels

### Search page
The `WIP banner` is over the top of the page banner, but the intention is to push the banner down, below the WIP banner so that they don't overlap
![Screen Shot 2020-08-20 at 9 10 50 AM](https://user-images.githubusercontent.com/7027270/90783070-3e4eae80-e2c5-11ea-8f67-3d0023ea6ea1.png)
- [ ] **Expected behavior**: ![Screen Shot 2020-08-20 at 9 12 38 AM](https://user-images.githubusercontent.com/7027270/90783109-4c9cca80-e2c5-11ea-97f5-0981ca3e0f94.png)

**Comment by chase-vert** [comment]
@jairPineros just for quick review

**Comment by robbobfrh84** [comment]
I just wanted to make a note that I scaled this as an 8 because the WIP banner is site-wide and it proved to be tricky when getting it work in one state, while not unintentionally altering another state. Takes quite a bit of testing and tinkering. 
- By state, i mean responsiveness, page type, dropdown state. etc. etc...
