### ISSUE TITLE
Create a reviewer checklist for dept content migration process

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#4788]
We have an editorial process, but we need a pared down version for the content migration process. 

- [x] Draft checklist
- [x] [Share w/ content](https://docs.google.com/document/d/1FVP_ZiQyT2P5F6GUNET327L6hyyexrkA-IzKXQjjzXw/edit#heading=h.7aga879dvzu9)
- [x] Incorporate any changes
- [x] Make sure it's in a place that makes sense and everyone knows where it is. Option: make a "migrate a page" issue template for fast-tracked content migration that includes a link to the checklist section when ready for review, plus all other relevant steps.
