### ISSUE TITLE
🚧 Filtering: custom date range ∙ Dev criteria

### ISSUE THREAD

**Issue by chase-vert** [cityofaustin/techstack#4849]
# Overview
This issue is for reviewing the mocks in the next sprint. Original issue: https://github.com/cityofaustin/techstack/issues/4773

Ahead of the work that dev is doing to support the next iteration of `Search` functionality, let's take a look at the addition of a `date picker` to make date inputs easier and more intuitive. 

## To-do
- [x] Review the existing date picker used in forms and evaluate
- [x] Screenreader accessibility
- [x] Add a `submit` button on desktop
- [x] Write out all of the edge cases
- [x] Write out all of the functional criteria

## Files
- Abstract branch: [Search filter: date pickers #4773](https://share.goabstract.com/ed0443c6-f82c-4b42-b541-a7ef66eb4eac)
- (New) Abstract branch: https://app.abstract.com/projects/065fcabf-a46a-4688-a858-83ce2117b16c/branches/3a2b0cf9-c911-4f50-a55f-51192d591bc2
- Drafting: https://share.goabstract.com/a59f413f-f21a-4ecc-98e7-21b60cc76b0e
- Dev criteria collection: https://share.goabstract.com/daf92a85-b140-4cf0-9b07-8e0f416ccd56

# Interactions
### Desktop
1. Resident inputs dates using any combination of the calendar input, or manual type input
2. Resident selects `Apply filters`
3. Page updates with filters applied, and includes the `Filter summary`

### Tablet and mobile
1. Resident clicks `Filter by date` button
2. Modal opens on top of the current screen
3. Resident inputs dates using any combination of the calendar input, or manual type input
4. Resident clicks `Apply filters`
5. Modal dissolves, returning the user to the original page, now with filtered results
- Beneath the `Filter by date` button, a `Filter summary` has been added to show the Resident that a filter is applied, how many results are within this filtered subset, and the ability to clear filters 
6. Clearing filters returns the document collection to its default state 

# Criteria

## Components
- Filter rail on the left side of the body content, in the box model this takes up 3 columns 
  - Label EN: "`Filter`"
  - Label ES: "``"
- Date range filter
  - Container
  - Label EN: "`Date`"
  - Label ES: "``"
  - From input fields
    - Month input field
    - Day input field
    - Year input field
    - Datepicker button
  - To input fields
     - Month input field
    - Day input field
    - Year input field
    - Datepicker button
  - Button: Apply filters
  - Button: Clear filters. This appears only after an input has been made
- Filter summary
  - Label "`#` filtered results" replace `#` with the number of results with the filter applied
  - Button: "Clear filters" 

## Input fields
- [x] Border-radius: 4px
- [x] Default state
  - [x] Background color: `#f3f3f3` or USWDS `gray-4`
- [x] Hover state
  - [x] Dropshadow: `#0050D8`, 24%; y position: 3px, x position: 6px
- [x] Focused state
  - [x] Border: 1px, `#0050D8` or USWDS `blue-warm-60v`
  - [x] Dropshadow: `#0050D8`, 24% opacity; x position: 0px, y position: 3px, blur: 6px
- [ ] Error state
  - [ ] Border: `#e51d3d` or USWDS `red-cool-50v`

### Label
- [x] Rail label
  - [x] EN: "Filter"
  - [x] ES: ""
- [x] Filter block label
  - [x] EN: "Date"
  - [x] ES: ""
  - [x] font-size: `18px`, weight: `medium` or `500`
  - [x] font-color: `#1b1b1b` or USWDS `gray-90`
- [x] Field label
  - [x] Font size: `14px`
  - [x] Text color: `#1b1b1b` or USWDS `gray-90`
- [ ] Description
  - [ ] Text color: `#5C5C5C` or USWDS `gray-60`
  - [ ] text size: `14px`
- [ ] Error text
  - [ ] Font-color: `#e51d3d` or USWDS `red-cool-50v`

## Buttons
**Clear filter: tablet and mobile**
- [x] Label 
  - [x] Label: EN: "``"
  - [x] Label ES: "``"
- [x] States
  - [x] Default: 
    - [x] Container background color: `#FFF2F5` or USWDS `red-cool-5v`
    - [x] Text color: `#E51D3D` or USWDS `red-cool-50v`
  - [x] Hover: no change

**Clear filter: desktop**
- [ ] Label 
  - [ ] EN: "`Clear filter`"
  - [ ] ES: "``"
- [ ] Trailing icon: named `close` in Material Icon font `#E51D3D`
- [ ] States
  - [ ] Default: `#E51D3D` or USWDS `red-cool-50v`, not underlined
  - [ ] Hover styling: underline

**Apply filter: desktop**
- [x] Label
  - [x] Label EN: "`Apply filter`"
  - [x] Label ES: "``"
- [x] Background color/container fill
  - [x] Default: `#EDF5FF` or USWDS `blue-warm-5v`
  - [x] Hover: primary blue `#0050D8` or USWDS `blue-warm-60v`
- [x] Text color
  - [x] Default state: primary blue `#0050D8` or USWDS `blue-warm-60v`
  - [x] Hover state: `#000000`

**Apply filter: tablet and mobile**
- [x] Leading icon: named `filter_list` in Material Icon font
- [x] States
  - [x] Default: primary blue `#0050D8` or USWDS `blue-warm-60v`
  - [x] Hover: no change]

**Calendar button**
- [x] Container background/fill: `#EDF5FF` or USWDS `blue-warm-5v`
- [x] Icon
  - [x]  Name: `event` in Material Icon font
  - [x] Icon color: primary blue `#0050D8` or USWDS `blue-warm-60v`
  
## Filter summary
- [ ] Padding
  - [ ] Desktop: `24px`
  - [ ] Tablet and mobile: `16px`
- [ ] Margin-bottom (between this component and the first item in the result list)
  - [ ] Desktop and tablet: `48px`
  - [ ] Mobile: `32px`
- [ ] Background color: `#f3f3f3` or `gray-4` in USWDS color palette
- [ ] Text colors
  - [ ] `# filtered results` set in default text color, which is `#1b1b1b` or USWDS `gray-90`
  - [ ] `Clear filters` label + the trailing `X` icon set in `#e51d3d` or USWDS `red-cool-50v`

**Style note for mobile**
On mobile, the filter summary is broken into two rows: 
- [ ] top row for the `# filter results`
  - [ ] Border-bottom: 1px, `#e6e6e6`
- [ ] another row for the `Clear filters` + trailing `X` icon
  - [ ] This entire row should be clickable
  - [ ] Hover color: `#fff2f5` or USWDS `red-cool-5v`

## Tablet and mobile

**Comment by chase-vert** [comment]
# Feedback to incorporate
- [ ] Add a `submit` button on desktop
- [ ] Write out all of the edge cases
- [ ] Write out all of the functional criteria

**Comment by Niicck** [comment]
How does library look to you? This would be my top pick. https://reactdatepicker.com/

**Comment by chase-vert** [comment]
Nice! This could work, and I really like the flexibility for lots of other use cases we might have as well.
