### ISSUE TITLE
Put images on info pages

### ISSUE THREAD

**Issue by Jo-Dwyer** [cityofaustin/techstack#4889]
## User story
As a content author I want to put images in the content of my page to enrich the experience for the user and increase the utility of the content type.

Design and content need to consider use cases for this.

## To-do
- [ ] Mock of info page in Joplin
- [ ] Mock of `Information page` on Janis
  - [ ] Spec margins for all breakpoints
  - [ ] Spec desired scaling behavior
- [ ] Update doc model
- [ ] Update style guide

### Janis
Abstract branch: https://share.goabstract.com/8c95ff5d-5bb2-42a5-8240-715dce9ca8c1
- [ ] Spec margins for all breakpoints
  - [ ] Desktop:
  - [ ] Tablet: 
  - [ ] Mobile: 
- [ ] Scaling behavior

cc @toribr and @Niicck

**Comment by toribr** [comment]
@cityofaustin/odd-devs 

Add images via rich text field on info pages.

**Comment by toribr** [comment]
Closing this one, as super MVP is imminent. We should write any new bugs/specs against that.
