### ISSUE TITLE
Dev Design Sync -- September 1, 2020

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/techstack#4891]
#### Dev
- [ ] `WIP banner` is positioned behind the `Department` header image

#### Design
- [x] Search v filtering on subsets: what we are thinking
- [x] What is a Top level page? UX #3619 (also ~~https://github.com/cityofaustin/techstack/issues/3051~~)
~~- [ ] Shouldn't roles be implemented before moderation?~~
- [ ] Events (online) Location is a requirement... do we add "online" here? Ref: https://github.com/cityofaustin/techstack/issues/4348 

## To-do
- [ ] @chase-vert to update `official docs` epic to include: `total # of docs` and `date filtering`
- [ ] @chase-vert to add the above `WIP banner` positioning issue into the existing issue
