### ISSUE TITLE
dev design sync, Tuesday Sep 15

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/techstack#4921]
Agenda

From dev
- [x] https://github.com/cityofaustin/techstack/issues/4787 - is this ready for devs?
- [x] https://github.com/cityofaustin/techstack/issues/4751 - redacted checkbox?
- [x] #4889 is there an issue for adding images from rich text fields?

From design
- [ ] There are a number of small Janis issues in "next sprint" that are ready for dev.
- [x] Date range in search
- [x] Add alt text field for media #4833 Where's this at?
      - [ ] see above from dev about images on RTF
- [x] #4348 Virtual event Joplin (https://share.goabstract.com/017dc239-f9fa-4300-94cf-198162b5ad36)
       - [ ] Can both virtual and physical be added?
- [x] Simple feedback https://share.goabstract.com/80af8fda-d36c-4e1a-8db1-62a1c335e741
- [ ] #3051 Improved copy
- [x] #4836 Dept and dept page flow
- [ ] #4718 Explicit close - how big of a deal?
- [ ] #2655 Scope this
- [ ] #4604 Can we go ahead and get this fixed?
- [ ] #2990 Did we decide tags or 3rd party?
- [x] #2253 Is this still relevant? -- no
