### ISSUE TITLE
Dev Design Sync Tuesday, September 22nd

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/techstack#4945]
Agenda

Dev
- [x] images on information pages (https://joplin-pr-4947-info-images.herokuapp.com/admin/pages/search/)
- [x] Date Picker!
- [x] https://joplin-pr-4897-no-tags.herokuapp.com/admin/images/

Design
From last week - suggest we postpone another week
- [ ] #3051 Improved copy
- [ ] #4718 Explicit close - how big of a deal?
- [ ] #2655 Scope this
- [ ] #4604 Can we go ahead and get this fixed?
- [ ] #2990 Did we decide tags or 3rd party?
