### ISSUE TITLE
Discuss with Dev how we can bring in more USWDS variables

### ISSUE THREAD

**Issue by chase-vert** [cityofaustin/techstack#4978]
## Background
We come to the conversation about variables and names pretty often these days, and we got some traction with `colors` recently this sprint. There are more variables that we can name to make implementation even smoother and consistent. 

## To-do
- [ ] Evaluate which variables make sense to bring over
- [ ] Talk about the effort to "tokenify" our work
- [ ] Is there any way that I can contribute to this? Know enough to change variables, limited to css/html; wouldn't be trying to do anything more than front-end styling stuff.
