### ISSUE TITLE
dev design sync, September 29

### ISSUE THREAD

**Issue by chiaberry** [cityofaustin/techstack#5017]
### Dev
- [ ] https://joplin-pr-4940-virtual-event.herokuapp.com/
- [ ] Browserstack is incoming

### Previous Design Topics
#4756 translatable contact (into ES only)
Mos MVP of the MVP-est
https://share.goabstract.com/36b0fe0b-9866-4e2c-beda-6f7b82ef25b5

From last week 
- [ ] #3051 Improved copy
- [ ] #4718 Explicit close - how big of a deal?
- [ ] #2655 Scope this
- [ ] #4604 Can we go ahead and get this fixed?
- [ ] #2990 Did we decide tags or 3rd party?
