### ISSUE TITLE
Language access blog post

### ISSUE THREAD

**Issue by srigdon** [cityofaustin/techstack#5091]
Let's write a Medium/Civiqueso/blog post about language access work. 

**To-dos before publishing**

[So, you wanna publish a Medium post?](https://docs.google.com/document/d/1KMFASGEiuEkWKdo4jeOmHZOfc02LKVsPiapxvD3IpkU/edit#heading=h.5zkr43xy0rg3)

<br>**Substance**<br>
Show what we did and how we did it:
- [ ] Lessons learned
- [ ] Research
- [ ] Implications

<br>**Content checklist:**<br>
- [ ] Refers to personas
- [ ] Quotes (1+)
- [ ] Photo or graphic (1+)
<br>**Process**<br>
- [ ] Create an issue in Github.
- [ ] Update and complete editorial calendar to set deadlines, ensure accountability and consistent content production. 
- [ ] Compose draft and edit. Aim to write at a grade 8 reading level.
- [ ] Complete A11y best practice checklist.
- [ ] Send to a member of the content team. Update issue and assign with requested deadline to return edits.
- [ ] Revise draft based on edits.
- [ ] Send back to member of the content team for final edits with requested deadline.
- [ ] Prep draft to publish on Medium.
<br>**Images**<br>
- [ ] Choose in-house, project, or public domain photos. Don’t use stock photos. 
- [ ] From in-house, project photos, make sure subjects in photos gave permission (signed a photo release) if they face the camera
- [ ] Favor active versus static subjects in photos.
- [ ] Specify dimensions:
Full column-width images: 1400 px
Out-set images: 2040 px
Screen-width images 2500 px
- [ ] Include one to two sentence caption that’s short, snappy and descriptive. 
<br>**Accessibility: Add Alt-Text to images in Google doc**<br>
- [ ] Select image in google doc
- [ ] Right click (On Mac - Control button + click). Select “Alt Text…”
- [ ] Author alt text
<br>**Add Alt-text to images in Medium.com**<br>
- [ ] Click edit story. Select an image in your story and choose alt text.
<br>**Publish**<br>
- [ ] Create an account on Medium.com.
- [ ] Hover the cursor over your profile photo or initial on (far upper right of screen). 
- [ ] Click, then scroll down to “New story.”
- [ ] Copy and paste your final draft. 
- [ ] Click “Ready to publish?” 
- [ ] **Disable "paywall" content button**<br>
<br>**Congrats! Your writing is out in the world**<br>
