### ISSUE TITLE
Janis Design System v2

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#725]
Doc: [Design System Process](https://docs.google.com/document/d/1R2HR9rQcO1dyVOjV-u0iMSVB744dkQFWSCWYncYlES8/edit#)

## Structure and Process
**Foundation (Perceptual Patterns)**
**Components (Functional Patterns)**

<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

- [ ] Establish foundation.

- [ ] Establish a pattern library.

- [ ] Set up master design files with up-to-date patterns.

- [ ] Refactor code and front-end architecture to support the modular approach.

- [ ] **Purpose and Values**: What users want, need, and their motivations. The purpose of the site, and the values we have for the community.

- [ ] **Design Principles**: Practical guidance on how to solve a design problem within the context of a specific product. What does good design mean for this product and the residents it serves?

- [ ] **Style**: Style tiles, mood boards, style guide

- [ ] Interface Audit

- [ ] Pattern map

- [ ] Storybook

**Comment by chasechenevert** [comment]
This issue is pretty stale now. I'll make a new issue that reflects the move into Abstract, and how that's changing the way we organize and communicate the design system
