### ISSUE TITLE
Janis v2 Design: Recollect / Trashy Design

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#849]
For the service page to be complete, the recollect app needs to be reskinned as part of Janis 2.0 design.
Scroll down to 'What do I do With' on the [bulk item pick page](http://alpha.austin.gov/services/bulk-item-pickup)

We have the ability to modify the CSS ONLY on these components as the code managed by a third party. Keep in mind applying css over third party app code is cumbersome and if changes are made to the code, often the css falls behind -- so styling overrides should be kept minimal. Also note there are multiple views in this app, so please click and search and use it's various feature to see all the views that need styling.

We also have our own Trashy app that could take the place of the Recollect look up schedule view. [Storybook for Trashy](http://alpha.austin.gov/storybook/?selectedKind=Trashy&selectedStory=Full%20component&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Factions%2Factions-panel)

**Comment by chasechenevert** [comment]
We want to look at this issue as a case study before we get to more instances of vendor applications that appear on Janis pages. 

**Research**
- [ ] Find 3 examples of third-party applications that will be resident-facing on Alpha. What are we able to change easily, what can't be changed easily?
- [ ] Find 3 examples from other Gov sites that use third-party applications on resident-facing pages. 

**Tasks**
- [ ] Ensure at least minimum accessibility requirements
- [ ] Specify how these applications should appear: styling, layout on page
- [ ] Specify interactions: state transitions, error/help messaging
- [ ] Document learning and solution ideas

**Comment by chasechenevert** [comment]
Here's the CSS for this app. We're pulling in a number of our Janis values (`.coa-`).

```
.coa-Trashy {
  border-left: none;
  border-right: none;
  margin: auto;
  padding: $coa-spacing-large $coa-spacing-medium;
  box-shadow: 0 1px 1px rgba(0, 0, 0, 0.05);
  border: 1px solid #ddd;
  box-sizing: border-box;
  border-radius: 4px;
}

.coa-Trashy__autosuggestion {
  border: solid 1px gray;
  padding: $coa-spacing-small;
  background-color: white;
}

.coa-Trashy__autosuggestion--highlighted {
  background-color: lightgray;
}

.coa-Trashy__autosuggestion-clear {
  position: relative;
  float: right;
  bottom: $coa-spacing-large + $coa-spacing-xsmall;
  right: $coa-spacing-small;
  background: white;
  height: $coa-font-size-medium;
}

// schedule styles
.coa-Trashy__schedule-container {
  box-sizing: border-box;
  display: flex;
  flex-direction: column;
  padding: $coa-spacing-medium;
}

.coa-Trashy__schedule-header {
  margin-bottom: $coa-spacing-large;
}

.coa-Trashy__schedule-list-container {
  display: flex;
  flex-direction: column;
  border: 1px solid #ddd;
  border-radius: 2px;
  padding: $coa-spacing-md-small;

  h4 {
    margin-bottom: $coa-spacing-small;
  }

  ul {
    list-style-type: none;
  }
}

.coa-Trashy__schedule-list-pickup-item {
  margin-bottom: $coa-spacing-medium;

  li {
    text-decoration: none;
  }
}

.coa-Trashy__schedule-bulk-pickup {
}
```

**Comment by chasechenevert** [comment]
Thinking through this one I think for the sake of bringing this closer into the fold of Janis we should just focus on a few key elements of the interface and otherwise leave it alone. We don't really know what will happen if/when the vendor updates this application so we need to be really cautious of overrides. 

We'll want to revisit this once we have more of an idea of other third-party applications we need on Alpha. I imagine they'll all come with certain limitations and affordances for skinning, but I think our sample size is way too small now to make any kind of long-term recommendation.

### Elements that need Janis styling: 
- [ ] Link color: #0049c7
- [ ] Button primary: background color: #0049c7; text: #ffffff
- [ ] Button secondary: background color: #ffffff; border: #0049c7; text: #212121
- [ ] Application banner should be set to #162E51
- [ ] Copy should be set in sentence case.

**Comment by chasechenevert** [comment]
Hey @desigonz I've assigned to you for next steps.

**Comment by desigonz** [comment]
Acceptance criteria captured in #2951.
